import datetime,decimal,json,pathlib
P=pathlib.Path(__file__).parent;B=P.parent;A=P/'access'
U='0x427c4b37de0714821b09c4fc655a713abbcfba83';Z='0x07ae8551be970cb1cca11dd7a11f47ae82e70e67';C='0x4216e5ae6021c523aae05b6ac6824f3c096cf905';T='0xec96957de4ececf24abd382090026e9b5c647405';V='0x3e2d81f7a5659e4760ba929ef88eed40ef6640a1';L='0x1231deb6f5749ef6ce6943a275a1d3e7486f4eae'
def raw(n):return json.loads((A/(n+'.response.txt')).read_text())
def r(n):return raw(n)['result']
def units(n):return format(decimal.Decimal(n)/10**18,'f')
def calls(t):
 yield t
 for x in t.get('calls',[]):yield from calls(x)
def stamp(b):return datetime.datetime.fromtimestamp(int(b['timestamp'],16),datetime.timezone.utc).isoformat()
def ef(*names):return ['access/'+n+'.response.txt' for n in names]
rows=[];edges=[]
def add(x):x={'ID':f'F{539+len(rows):04}',**x};rows.append(x);return x
oldedges=json.loads((B/'robinhood_linkage_2026_10_09/cross_chain_edges.json').read_text())
for e in oldedges[8:]:
 tag=e['origin_record_ID'];t=r(tag+'_fill_tx');q=r(tag+'_fill_receipt');b=r(tag+'_fill_block');trace=r(tag+'_callback_trace');n=int(e['destination_amount_wei']);cs=list(calls(trace));credit=[x for x in cs if x.get('from')==C and x.get('to')==U and int(x.get('value','0x0'),16)==n];unwrap=[x for x in cs if x.get('from')=='0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2' and x.get('to')==C and int(x.get('value','0x0'),16)==n];assert len(credit)==len(unwrap)==1 and not any(x.get('error') for x in cs)
 event=next(x for x in q['logs'] if x['address']==e['destination_pool']);assert event['topics'][2]=='0x'+format(int(e['deposit_id']),'064x') and format(n,'064x') in event['data']
 x=add({'classification':'CONFIRMED','record_type':'Ethereum callback native credit; enrichment of existing cross-chain edge, not additional loss','chain':'Ethereum (1)','transaction_hash':t['hash'],'existing_cross_chain_ID':e['ID'],'existing_origin_ID':tag,'protocol_identifier':e['deposit_id'],'outer_sender_relayer':t['from'],'callback_contract':C,'destination_wallet':U,'asset':'native ETH after WETH unwrap','amount_wei':str(n),'amount_ETH':units(n),'block_number':int(t['blockNumber'],16),'timestamp_UTC':stamp(b),'status':'success','fill_event':event,'native_unwrap_call':unwrap[0],'native_credit_call':credit[0],'evidence_files':ef(tag+'_fill_tx',tag+'_fill_receipt',tag+'_fill_block',tag+'_callback_trace'),'attribution_significance':'Exact same-transaction call trace closes callback-to-routing-wallet credit. Does not establish upstream affected-fund allocation, common ownership with relayer, or beneficiary.'});edges.append(x)
add({'classification':'CONFIRMED','record_type':'Already-funded Ethereum pool and sender-role separation','routing_wallet':U,'balance_before_first_Robinhood_fill_wei':str(int(r('routing_wallet_pre_first_fill_balance'),16)),'balance_before_F0127_wei':str(int(r('routing_wallet_pre_terminal_balance'),16)),'funding_provenance':'MIXED / pooled boundary; particular Robinhood-to-disposal allocation UNRESOLVED','account_overlap':'Seven Ethereum fill transactions freshly reproduced from 0x07ae; same full transaction-sender address as seven Robinhood zero-value submissions. This is an account-level sender observation, not common ownership with 0x427c, operator identity or custody.','limitation':'Nonzero pre-first-fill balance proves prior native liquidity, not its ownership or origin. Earlier verified Base and Robinhood routes remain separate. No FIFO/exact-amount attribution imposed.','evidence_files':ef('routing_wallet_pre_first_fill_balance','routing_wallet_pre_terminal_balance'),'attribution_significance':'Identifies an allocation boundary; does not add losses.'})
def txrow(tag,kind):
 t=r(tag+'_tx');q=r(tag+'_receipt');b=r(tag+'_block');return {'classification':'CONFIRMED','record_type':kind,'chain':'Ethereum (1)','transaction_hash':t['hash'],'source_wallet':t['from'],'destination_address':t['to'],'asset':'native ETH','amount_wei':str(int(t['value'],16)),'amount_ETH':units(int(t['value'],16)),'block_number':int(t['blockNumber'],16),'timestamp_UTC':stamp(b),'sender_nonce':int(t['nonce'],16),'status':'success','network_fee_wei':str(int(q['gasUsed'],16)*int(q['effectiveGasPrice'],16)),'input':t['input'],'evidence_files':ef(tag+'_tx',tag+'_receipt',tag+'_block'),'attribution_significance':'Direct account-level edge, not owner identity or additional loss; specific allocation of Robinhood funds remains unresolved.'}
x=txrow('terminal','Fresh reproduction of existing F0127 disposal');x.update({'existing_ID':'F0127','recipient_account_type':'EOA at case block','case_code':r('terminal_case_code'),'recipient_balance_before_incoming_wei':str(int(r('forwarder_pre_incoming_balance'),16)),'funding_provenance':'PARTIAL / RE-ESTABLISHED local receiving boundary; Ethereum routing wallet pooled upstream','evidence_files':x['evidence_files']+ef('terminal_case_code','forwarder_pre_incoming_balance')});add(x)
x=txrow('onward','New confirmed EOA onward edge');x.update({'source_account_type':'EOA at incoming case block','destination_account_type':'EOA at onward case block','destination_case_code':r('onward_case_code'),'source_pre_onward_balance_wei':str(int(r('forwarder_pre_onward_balance'),16)),'destination_pre_incoming_balance_wei':str(int(r('onward_recipient_pre_balance'),16)),'funding_provenance':'PARTIAL / RE-ESTABLISHED local forwarder: zero prior balance, matching incoming balance before nonce-zero outward transfer; pooled Robinhood allocation not repaired','evidence_files':x['evidence_files']+ef('forwarder_pre_onward_balance','onward_recipient_pre_balance','onward_case_code','terminal_transactions','terminal_internal-transactions')});edges.append(add(x))
x=txrow('supplement','New confirmed supplemental funding into second EOA');x.update({'funding_role':'Additional native liquidity before router call; gas-funding interpretation SUPPORTED, not owner/control attribution','evidence_files':x['evidence_files']+ef('onward_recipient_pre_router_balance')});edges.append(add(x))
x=txrow('router','New confirmed native input into verified LI.FI router');x.update({'protocol':'LI.FI Diamond','protocol_contract':L,'protocol_metadata_name':raw('router_metadata')['name'],'protocol_metadata_verified':raw('router_metadata')['is_verified'],'case_code_nonempty':len(r('router_case_code'))>2,'source_pre_router_balance_wei':str(int(r('onward_recipient_pre_router_balance'),16)),'funding_provenance':'MIXED at two-inflow EOA; transaction amount is verified, exclusive previous-inflow allocation not asserted','protocol_events':r('router_receipt')['logs'],'service_boundary':'CONFIRMED LI.FI router; no private custody or exchange-account holder identified','evidence_files':x['evidence_files']+ef('router_metadata','router_case_code','lifi_primary_docs','onward_recipient_pre_router_balance')});edges.append(add(x))
d=raw('router_lifi_status');add({'classification':'SUPPORTED','record_type':'Transaction-specific protocol API downstream lead, not yet independently verified destination settlement','source_transaction':d['sending']['txHash'],'protocol_identifier':d['transactionId'],'underlying_protocol_reported':d['tool'],'destination_chain_id_reported':d['receiving']['chainId'],'destination_transaction_reported':d['receiving']['txHash'],'destination_asset_reported':d['receiving']['token']['symbol'],'destination_amount_base_units_reported':d['receiving']['amount'],'destination_recipient_reported':d['toAddress'],'API_status':d['status'],'integrator_string':d['metadata']['integrator'],'fee_limit':'Empty API feeCosts is not proof of zero protocol fees or spread. Native transaction gas separately reproduced.','evidence_files':ef('router_lifi_status','router_receipt'),'attribution_significance':'Primary LI.FI response gives exact Mayan Ethereum-to-Arbitrum candidate. Destination receipt, matching Mayan order and downstream disposal not independently reproduced in this block. Cow is an integrator string, not named operator/owner evidence.'})
add({'classification':'UNRESOLVED','record_type':'Funding/disposal limits and next target','funding_summary':'Eight direct origin bridge entries remain UNRESOLVED upstream; seven Gateway prefunds are PARTIAL / RE-ESTABLISHED last-hop funding. No complete CLEAN affected-wallet native provenance. Ethereum routing account is already-funded pooled boundary; second disposal EOA receives supplemental liquidity.','beneficiary_attribution_advanced':False,'new_private_custody_or_exchange_attribution':False,'lookalike_warning':'Later dust sender 0x3e2df1a63dd295891663bb1697375e3df46d40a1 is distinct from actual forwarder 0x3e2d81f7a5659e4760ba929ef88eed40ef6640a1; no identity/control finding from address resemblance.','remaining_gaps':['Robinhood token-sale native payout traces and historical balances','Complete native upstream allocation and earlier fee funding','User authorization/control and independent service identities','Independent Mayan destination settlement for new exact LI.FI API candidate'], 'next_highest_priority_target':'Reproduce exact new Mayan destination hash and order correspondence from the 10.251 ETH disposal; do not assign individual pooled Robinhood deposits without native provenance.','preservation':'Six Relay routes/totals unchanged; old bridge routes not counted as new losses. Privacy Cash separate. No article; no identity/custody/common-owner findings.','evidence_files':ef('terminal_transactions','onward_transactions')})
assert rows[-1]['ID']=='F0552'
old=json.loads((B/'robinhood_funding_gateway_2026_10_09/master_timeline_F0001_F0538.json').read_text())['rows']
(P/'ledger_F0539_F0552.json').write_text(json.dumps(rows,indent=2)+'\n');(P/'master_timeline_F0001_F0552.json').write_text(json.dumps({'notes':'Prior 538 objects preserved exactly. Callback completion and direct disposal edges do not allocate pooled Robinhood proceeds or add losses.','rows':old+rows},indent=2)+'\n');(P/'disposal_edges.json').write_text(json.dumps(edges,indent=2)+'\n')
