import datetime,decimal,hashlib,json,pathlib
P=pathlib.Path(__file__).parent;A=P/'access';B=P.parent;D=decimal.Decimal;U='0xae06669dfd3e932476f00ea49fce82e5e63f83bf'
def raw(n):return json.loads((A/(n+'.response.txt')).read_text())
def write(n,d):(P/n).write_text(json.dumps(d,indent=2)+'\n')
history=raw('ordinary_history')['result'];out=[x for x in history if x['from'].lower()==U];ins=[x for x in history if x['to'].lower()==U];prior=json.loads((B/'robinhood_disposal_settlement_2026_10_09/funding_edges.json').read_text());byhash={x['hash']:x for x in history};case=[byhash[x['transaction_hash']] for x in prior];total=sum(D(x['value'])/10**18 for x in case)
summary={'source':U,'chain':'Ethereum 1','startblock':26130000,'endblock':26137480,'ordinary_records':len(history),'outgoing_records':len(out),'unique_outgoing_recipients':len(set(x['to'].lower() for x in out)),'outgoing_nonce_min':min(int(x['nonce']) for x in out),'outgoing_nonce_max':max(int(x['nonce']) for x in out),'outgoing_transfers_exactly_0_0015_ETH':sum(x['value']=='1500000000000000' for x in out),'case_relevant_count':len(case),'case_relevant_total_ETH':str(total),'case_nonce_sequence':[int(x['nonce']) for x in case],'first_observed_case_funding_UTC':datetime.datetime.fromtimestamp(int(case[0]['timeStamp']),datetime.timezone.utc).isoformat(),'last_observed_case_funding_UTC':datetime.datetime.fromtimestamp(int(case[-1]['timeStamp']),datetime.timezone.utc).isoformat(),'first_lifetime_funding':'UNRESOLVED / not examined','internal_records_returned':len(raw('internal_history')['result']),'ordinary_inbound_count':len(ins),'direct_root_wallet_links_in_scope':[],'service_or_identity':'UNRESOLVED: captured metadata has no name/public tags; empty case code establishes EOA status, not identity','upstream_allocation':'No inbound-to-ten-payments exclusive allocation; existing balances not reconciled here','branch_status':'CLOSED at scoped funding-account relationship; no recipient fan-out; incoming sender retained as bounded lead only'}
write('summary.json',summary);write('case_recipient_inventory.json',[{'existing_ID':x['ID'],'transaction_hash':x['transaction_hash'],'recipient':x['destination_wallet'],'ETH':x['amount_ETH'],'nonce':x['sender_nonce'],'timestamp_UTC':x['timestamp_UTC'],'ordinary_history_record':byhash[x['transaction_hash']],'previous_evidence_files':['../robinhood_disposal_settlement_2026_10_09/'+f for f in x['evidence_files']]} for x in prior])
rows=[]
def add(kind,evidence,details):rows.append({'ID':f'F{594+len(rows):04}','classification':'CONFIRMED','record_type':kind,'evidence_files':evidence,'details':details,'limits':'Scoped account relationships only. No common control, user-signature recovery, service/custody identity, affected-wallet allocation or beneficiary attribution.'})
add('Existing ten case funding edges: bounded inventory and totals enrichment',['access/ordinary_history.response.txt','case_recipient_inventory.json','../robinhood_disposal_settlement_2026_10_09/funding_edges.json'],{k:summary[k] for k in ['source','case_relevant_count','case_relevant_total_ETH','case_nonce_sequence','first_observed_case_funding_UTC','last_observed_case_funding_UTC','first_lifetime_funding']})
add('Bounded explorer funding pattern and role separation',['access/ordinary_history.response.txt','access/internal_history.response.txt','access/ordinary_history.json','access/internal_history.json'],{k:summary[k] for k in ['startblock','endblock','ordinary_records','outgoing_records','unique_outgoing_recipients','outgoing_nonce_min','outgoing_nonce_max','outgoing_transfers_exactly_0_0015_ETH','internal_records_returned','direct_root_wallet_links_in_scope']})
t=raw('inbound_tx')['result'];q=raw('inbound_receipt')['result'];b=raw('inbound_block')['result']
add('New independently reproduced native funding edge into common source',['access/inbound_tx.response.txt','access/inbound_receipt.response.txt','access/inbound_block.response.txt','access/funder_case_code.response.txt','access/inbound_sender_case_code.response.txt'],{'transaction_hash':t['hash'],'source':t['from'],'destination':t['to'],'ETH':str(D(int(t['value'],16))/10**18),'wei':str(int(t['value'],16)),'timestamp_UTC':datetime.datetime.fromtimestamp(int(b['timestamp'],16),datetime.timezone.utc).isoformat(),'sender_nonce':int(t['nonce'],16),'gasUsed':int(q['gasUsed'],16),'effectiveGasPrice_wei':int(q['effectiveGasPrice'],16),'sender_gas_ETH':str(D(int(q['gasUsed'],16)*int(q['effectiveGasPrice'],16))/10**18),'input':t['input'],'case_code':'both source and destination empty; ordinary EOA transfer includes nonempty calldata, not evidence of a contract call','allocation':'UNRESOLVED: no exclusive propagation from this inflow into case payments'})
add('Dated metadata and explicit attribution stop boundary',['access/metadata.response.txt','access/inbound_sender_metadata.response.txt','access/metadata.json','access/inbound_sender_metadata.json'],{'source':U,'inbound_sender':t['from'],'service_attribution':'UNRESOLVED / no identifying metadata','beneficiary':'UNRESOLVED','known_case_root_wallet_direct_link':'No direct ordinary transaction in bounded captured history with 0x427c, 0x07ae or reported affected EVM wallet; not lifetime absence','branch_status':summary['branch_status'],'next_bounded_lead':'Identify the exact inbound sender only if independent service/identity evidence becomes available; do not fan-out recipients'})
write('ledger_F0594_F0597.json',rows);old=json.loads((B/'hyperliquid_matched_account_2026_10_10/master_timeline_F0001_F0593.json').read_text())['rows'];write('master_timeline_F0001_F0597.json',{'rows':old+rows})
