"""Append direct-role funding observations without assigning unavailable balances."""
import datetime,decimal,hashlib,json,pathlib
P=pathlib.Path(__file__).parent; A=P/'access'; B=P.parent
OLD=B/'unlabeled_a3ca_verification_2026_10_09/master_timeline_F0001_F0504.json'
def raw(n):return json.loads((A/(n+'.response.txt')).read_text())
def r(n):return raw(n)['result']
def units(n):return format(decimal.Decimal(n)/10**18,'f')
T='0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'
U='0x427c4b37de0714821b09c4fc655a713abbcfba83'; V='0x14aa2a71dbb5ef87b81f92205e2699aa4aa65794'
origins=[x for x in json.loads((B/'robinhood_linkage_2026_10_09/transaction_ledger_F0435_F0464.json').read_text()) if x['record_type']=='origin deposit']
rows=[]
def add(x):x={'ID':f'F{505+len(rows):04}',**x};rows.append(x);return x
def evidence(labels):return ['access/'+x+'.response.txt' for x in labels]
for o in origins[:8]:
    q=r(o['ID']+'_receipt');assert q['transactionHash']==o['transaction_hash'] and q['status']=='0x1'
    add({'classification':'CONFIRMED','record_type':'Direct Robinhood bridge-input reproduction; funding state unresolved','chain':'Robinhood Chain (4663)','existing_origin_ID':o['ID'],'source_transaction':o['transaction_hash'],'sender':o['sender'],'recipient':o['transaction_recipient'],'deposit_id':o['deposit_id'],'block_number':o['block_number'],'timestamp_UTC':o['timestamp_UTC'],'asset':'native ETH → wrapped-native Across input','input_amount_wei':o['input_amount_wei'],'input_amount_ETH':units(int(o['input_amount_wei'])),'status':'success','funding_provenance':'UNRESOLVED','case_attributable_amount':'UNRESOLVED; no deterministic allocation from prior native balance','prior_balance_observation':raw(o['ID']+'_pre_balance'),'post_balance_observation':raw(o['ID']+'_post_balance'),'prior_nonce_observation':raw(o['ID']+'_pre_nonce'),'fee_wei':str(int(q['gasUsed'],16)*int(q['effectiveGasPrice'],16)),'evidence_files':evidence([o['ID']+'_receipt',o['ID']+'_pre_balance',o['ID']+'_post_balance',o['ID']+'_pre_nonce']),'attribution_significance':'Same direct transaction sender and native value role, not ownership of any other sender, complete affected-wallet provenance or extra loss.'})
source_hashes=['0x49e05a92a0b08841fac2b475877cd02732e957412d0e1a3cad706f489641c596','0xbf1158177a2f350f092b2426025b339bfeeaa77923e4e51c6bb216d3292b8171','0xa71e132f397b427cc6f1bb58252a5c56b2e0a5dde14733c840103ec3552456a7']
tokens={};source_amount={}
for h,asset,oldid in zip(source_hashes,['CASHCAT','V4','wrapped native'],['F0187','F0188','F0189']):
    t=r(h+'_tx');q=r(h+'_receipt');b=r('block_'+t['blockNumber']);assert q['status']=='0x1' and t['blockHash']==q['blockHash']==b['hash']
    l=next(x for x in q['logs'] if x['topics'][0]==T and '0x'+x['topics'][1][-40:]==V and '0x'+x['topics'][2][-40:]==U)
    tokens[asset]=l['address'];source_amount[asset]=int(l['data'],16)
    add({'classification':'CONFIRMED','record_type':'Fresh affected-wallet token funding reproduction; existing transfer not new loss','existing_ID':oldid,'chain':'Robinhood Chain (4663)','source_transaction':h,'transaction_sender':t['from'],'source_wallet':V,'destination_wallet':U,'token':l['address'],'asset_label':asset+' (prior metadata)','raw_amount':str(int(l['data'],16)),'amount_18_decimals':units(int(l['data'],16)),'block_number':int(t['blockNumber'],16),'timestamp_UTC':datetime.datetime.fromtimestamp(int(b['timestamp'],16),datetime.timezone.utc).isoformat(),'funding_provenance':'PARTIAL / RE-ESTABLISHED at token transfer only','prior_token_balance':'UNRESOLVED; historical state unavailable','attribution_significance':'Direct token edge from the reported affected address is reproduced; does not assign its whole subsequent balance to incident funds. Wallet identity/compromise method are not re-established here.','evidence_files':evidence([h+'_tx',h+'_receipt','block_'+t['blockNumber']])})
swaps=['0x38ccc85e35a54234662a915df3c21b875f5d3e0adac5d9caa9eb44cc9fabf5eb','0xae6a813e60f259eb90516ecc2fd26680d86bb0cab9a1b5b18c660c737fd68c8f','0x2b65933dc34cd4283fbe1d5a0c90d2e82a07ea88b96a7acbe639560eae8887a8'];v4_total=0;burn_total=0
for h in swaps:
    t=r(h+'_tx');q=r(h+'_receipt');b=r('block_'+t['blockNumber'])
    debits=[x for x in q['logs'] if x['address']==tokens['V4'] and x['topics'][0]==T and '0x'+x['topics'][1][-40:]==U]
    burns=[x for x in q['logs'] if x['address']==tokens['wrapped native'] and x['topics'][0]==T and int(x['topics'][2],16)==0]
    n=sum(int(x['data'],16) for x in debits);m=sum(int(x['data'],16) for x in burns);v4_total+=n;burn_total+=m
    add({'classification':'CONFIRMED','record_type':'New V4 disposal token debits and wrapped-native burns; native payout allocation unresolved','chain':'Robinhood Chain (4663)','source_transaction':h,'transaction_sender':t['from'],'transaction_recipient':t['to'],'nonce':int(t['nonce'],16),'selector':t['input'][:10],'block_number':int(t['blockNumber'],16),'timestamp_UTC':datetime.datetime.fromtimestamp(int(b['timestamp'],16),datetime.timezone.utc).isoformat(),'V4_source_wallet':U,'V4_token':tokens['V4'],'V4_raw_debit':str(n),'V4_amount':units(n),'token_debit_events':debits,'wrapped_native_burn_amount':units(m),'wrapped_native_burn_events':burns,'funding_provenance':'PARTIAL / RE-ESTABLISHED token-level disposal; bridge-input provenance UNRESOLVED','native_payout_recipient':'UNRESOLVED; no call trace or historical balances','service_attribution':'Contract-mediated swap behavior; named operator/custody not independently identified for this Robinhood deployment','evidence_files':evidence([h+'_tx',h+'_receipt','block_'+t['blockNumber']]),'attribution_significance':'Token-debit source and outer sender remain distinct. Native burn is not silently recorded as a verified native credit to the case sender.'})
assert v4_total==source_amount['V4']
h='0x16d4895a9cf3a1e415c908b38108c7cdb271b87496c3199bde8eb7b544465f47';t=r(h+'_tx');q=r(h+'_receipt');b=r('block_'+t['blockNumber']);burn=next(x for x in q['logs'] if x['topics'][0]==T and int(x['topics'][2],16)==0)
assert t['from']==U and t['to']==tokens['wrapped native'] and t['input'][:10]=='0x2e1a7d4d' and int(t['input'][10:74],16)==source_amount['wrapped native']==int(burn['data'],16)
add({'classification':'CONFIRMED','record_type':'New exact wrapped-native withdraw call and burn','chain':'Robinhood Chain (4663)','source_transaction':h,'sender':U,'contract':t['to'],'nonce':int(t['nonce'],16),'withdraw_call_amount':units(int(burn['data'],16)),'withdraw_call_amount_wei':str(int(burn['data'],16)),'block_number':int(t['blockNumber'],16),'timestamp_UTC':datetime.datetime.fromtimestamp(int(b['timestamp'],16),datetime.timezone.utc).isoformat(),'burn_event':burn,'funding_provenance':'PARTIAL / RE-ESTABLISHED withdrawal action; exclusive affected-wallet allocation and bridge deposit linkage UNRESOLVED','native_payout_trace':'Unavailable; native balance reconciliation not independently performed','evidence_files':evidence([h+'_tx',h+'_receipt','block_'+t['blockNumber'],'unwrap_trace'])})
q=r('first_cashcat_receipt');t=r('first_cashcat_tx');b=r('first_cashcat_block');burns=[x for x in q['logs'] if x['address']==tokens['wrapped native'] and x['topics'][0]==T and int(x['topics'][2],16)==0]
add({'classification':'CONFIRMED','record_type':'Fresh F0196 CASHCAT disposal and newly recorded wrapped-native burn','chain':'Robinhood Chain (4663)','source_transaction':t['hash'],'transaction_sender':t['from'],'transaction_recipient':t['to'],'CASHCAT_source_wallet':U,'CASHCAT_amount':'1100227.867433114634814141','wrapped_native_burn_amount':units(sum(int(x['data'],16) for x in burns)),'wrapped_native_burn_events':burns,'block_number':int(t['blockNumber'],16),'timestamp_UTC':datetime.datetime.fromtimestamp(int(b['timestamp'],16),datetime.timezone.utc).isoformat(),'funding_provenance':'PARTIAL / RE-ESTABLISHED token disposal; native payout and subsequent bridge allocation UNRESOLVED','evidence_files':evidence(['first_cashcat_tx','first_cashcat_receipt','first_cashcat_block','first_cashcat_trace']),'attribution_significance':'A swap/burn observation, not a clean provenance reconstruction or assignment of outer sender control to the token owner.'})
code=r('direct_snapshot_code');assert code=='0xef010063c0c19a282a1b52b07dd5a65b58948a07dae32b'
add({'classification':'CONFIRMED','record_type':'Dated EIP-7702 delegation-designator snapshot','address':U,'chain':'Robinhood Chain (4663)','block_number':int(r('snapshot_block')['number'],16),'timestamp_UTC':datetime.datetime.fromtimestamp(int(r('snapshot_block')['timestamp'],16),datetime.timezone.utc).isoformat(),'account_code':code,'delegation_target':'0x63c0c19a282a1b52b07dd5a65b58948a07dae32b','target_framework_association':'SUPPORTED: MetaMask first-party deployment list names EIP7702StatelessDeleGatorImpl at this address. No Robinhood target bytecode/deployment audit or historical-code proof.','case_control_limit':'A self-addressed successful V4 transaction contains token/pool effects; current delegation snapshot cannot establish when delegation began, wallet software used, key ownership or compromise. No shared-owner link to 0x07ae…0e67.','evidence_files':evidence(['direct_snapshot_code','snapshot_block','direct_case_code','metamask_deployments','eip7702_spec'])})
add({'classification':'UNRESOLVED','record_type':'Direct-role funding closure and evidence limits','direct_origin_routes':8,'exact_direct_bridge_input_ETH':units(sum(int(x['input_amount_wei']) for x in origins[:8])),'V4_total_debit':units(v4_total),'V4_total_wrapped_native_burn':units(burn_total),'funding_provenance':'UNRESOLVED into all eight native bridge entries; PARTIAL token-source/disposal reconstruction only','missing':['Historical native/token balances','Complete native inflow history','Native payout call traces','Fee-funder identity/transaction reconstruction','Deterministic case-funds allocation to each bridge input'],'state_observation_note':'All attempted historical balance/nonce reads and sample debug traces failed. Successful HTTP status is not successful RPC state retrieval. Explorer failures are not absence evidence.','bounded_log_window':[81901837,82032267],'scope':'Indexed-topic searches at positions 1/2 only, not all internal/native activity or earlier account history. Exact token-debit totals equal observed affected inbound totals but equality alone does not prove exclusive provenance.','other_sender_group':'Seven zero-value 0x07ae…0e67 routes remain separate; preliminary shared state/trace attempts are saved without allocating its balance to case assets.','next_target':'Contract-mediated order/asset-source reconstruction for the seven zero-value outer transactions','attribution_significance':'No CLEAN origin, common fee funder, common owner/operator, private custody or final beneficiary established; routing and new observations do not add loss amounts.'})
assert rows[-1]['ID']=='F0522'
old=json.loads(OLD.read_text());out={'notes':'F0001–F0504 objects preserved exactly. Token-level edges and native burns are not exclusive funding allocations. State failures are explicit. No article or additional losses; Privacy Cash separate.','rows':old['rows']+rows}
(P/'ledger_F0505_F0522.json').write_text(json.dumps(rows,indent=2)+'\n');(P/'master_timeline_F0001_F0522.json').write_text(json.dumps(out,indent=2)+'\n')
(P/'summary.json').write_text(json.dumps({'funding_provenance':'UNRESOLVED','token_level_provenance':'PARTIAL / RE-ESTABLISHED','direct_bridge_input_ETH':units(sum(int(x['input_amount_wei']) for x in origins[:8])),'V4_debit':units(v4_total),'V4_burn':units(burn_total),'new_ID_range':['F0505','F0522'],'new_native_credit_edges':0,'beneficiary_attribution_advanced':False},indent=2)+'\n')
