import datetime,decimal,hashlib,json,pathlib
from protocol import gateway_path,keccak
P=pathlib.Path(__file__).parent;B=P.parent;A=P/'access'
def raw(n):return json.loads((A/(n+'.response.txt')).read_text())
def r(n):return raw(n)['result']
def units(n):return format(decimal.Decimal(n)/10**18,'f')
def words(l):return [l['data'][2+i*64:2+(i+1)*64] for i in range((len(l['data'])-2)//64)]
def stamp(b):return datetime.datetime.fromtimestamp(int(b['timestamp'],16),datetime.timezone.utc).isoformat()
def ef(labels):return ['access/'+x+'.response.txt' for x in labels]
G='0x998d7c178a1f9607b47ea3a8e22426451b3ce707';F='0x794dbdbdbfd3f8a3b887f4513bf5ff29edd04a94';U='0x427c4b37de0714821b09c4fc655a713abbcfba83';Z='0x07ae8551be970cb1cca11dd7a11f47ae82e70e67';E='0xa5166c3e69a933ee547ad908c9f1474f8f61901a'
stored='0x'+keccak(b'PrefundingStored(bytes32,address,uint256)');funded='0x'+keccak(b'PrefundedFunding(bytes32,address,uint256,address)');step='0x'+keccak(b'StepExecuted(bytes32,bytes32,address)')
origins=[x for x in json.loads((B/'robinhood_linkage_2026_10_09/transaction_ledger_F0435_F0464.json').read_text()) if x['record_type']=='origin deposit'][8:];logs=[]
for f in A.glob('escrow_step_logs_*.response.txt'):logs+=json.loads(f.read_text())['result']
rows=[];edges=[]
def add(x):x={'ID':f'F{523+len(rows):04}',**x};rows.append(x);return x
for o in origins:
    tag=o['ID'];t=r(tag+'_tx');q=r(tag+'_receipt');b=r(tag+'_block');s=next(x for x in q['logs'] if x['topics'][0]==step and x['address']==G);sid=s['topics'][1]
    matching=[x for x in logs if x['topics'][0]==stored and x['topics'][1]==sid];assert len(matching)==1;deposit=matching[0];h=deposit['transactionHash'];pt=r(h+'_tx');pq=r(h+'_receipt');pb=r('block_'+pt['blockNumber']);pw=words(deposit);n=int(pw[1],16)
    assert int(pw[0],16)==0 and pt['from']==U and pt['to']==F and int(pt['value'],16)==n==int(o['input_amount_wei'])
    assert pt['input'][:10]=='0x'+keccak(b'store(bytes32,address,uint256)')[:8] and pt['input'][10:74]==sid[2:] and int(pt['input'][74:138],16)==int(pt['input'][138:202],16)==0
    assert t['from']==Z and t['to']==G and int(t['value'],16)==0
    release=next(x for x in q['logs'] if x['address']==F and x['topics'][0]==funded and x['topics'][1]==sid);rw=words(release);assert rw[:2]==pw and '0x'+rw[2][-40:]==E
    path=gateway_path(t,s);assert path['executor']==E and '0x'+s['data'][-40:]==Z
    dep=next(x for x in q['logs'] if x['topics'][0]=='0x'+keccak(b'FundsDeposited(bytes32,bytes32,uint256,uint256,uint256,uint256,uint32,uint32,uint32,bytes32,bytes32,bytes32,bytes)'));assert int(words(dep)[2],16)==n
    a=add({'classification':'CONFIRMED','record_type':'New native prefunding edge','chain':'Robinhood Chain (4663)','source_transaction':h,'source_wallet':pt['from'],'destination_contract':F,'asset':'native ETH','amount':units(n),'amount_wei':str(n),'block_number':int(pt['blockNumber'],16),'timestamp_UTC':stamp(pb),'sender_nonce':int(pt['nonce'],16),'status':'success','protocol_identifier':sid,'protocol_native_event':deposit,'input_call':'store(witness, zero-token, zero-token-amount) with attached native value','funding_provenance':'PARTIAL / RE-ESTABLISHED: exact last-hop native funding; prior 0x427c balance provenance UNRESOLVED','case_attributable_amount':'UNRESOLVED upstream of this native prefunding transaction','network_fee_wei':str(int(pq['gasUsed'],16)*int(pq['effectiveGasPrice'],16)),'evidence_files':ef([h+'_tx',h+'_receipt','block_'+pt['blockNumber']]),'attribution_significance':'Origin source is 0x427c, not zero-value outer sender 0x07ae. Account roles only; no private custody, common owner or additional loss.'})
    e=add({'classification':'CONFIRMED','record_type':'New transaction-specific prefund-to-bridge funding edge','chain':'Robinhood Chain (4663)','funding_transaction':h,'source_transaction':o['transaction_hash'],'existing_bridge_origin_ID':tag,'existing_cross_chain_ID':f'F{int(tag[1:])+1:04}','native_source_wallet':U,'outer_transaction_sender':Z,'outer_native_value_wei':'0','prefunded_adapter':F,'execution_contract':E,'bridge_contract':o['deposit_contract'],'wrapped_native_token':o['deposited_token'],'amount_wei':str(n),'amount_ETH':units(n),'protocol_identifier':sid,'deposit_id':o['deposit_id'],'gateway_path':path,'native_release_event':release,'gateway_event':s,'bridge_deposit_event':dep,'block_number':int(t['blockNumber'],16),'timestamp_UTC':stamp(b),'funding_provenance':'PARTIAL / RE-ESTABLISHED at exact native prefunding boundary; complete affected-wallet provenance UNRESOLVED','matched_parameters':['same witness/step ID','native token sentinel','stored/released/minted/deposited amount','prefunding transaction attached value','prefund recipient equals path executor','Gateway chain ID and path hash','independently validated Merkle root','actual submitter versus native funder'],'evidence_files':ef([tag+'_tx',tag+'_receipt',tag+'_block','escrow_eth_metadata']), 'attribution_significance':'Per-witness protocol correspondence, not timing or amount similarity. Existing cross-chain edge is not counted again. EIP712/user-signature ownership validation not performed.'});edges.append(e)
state=r('snapshot');pref=r('prefunded_snapshot_code');meta=raw('escrow_eth_metadata');same=pref.lower()==meta['deployed_bytecode'].lower()
add({'classification':'CONFIRMED','record_type':'Protocol-role/current-code snapshot; historical audit limited','chain':'Robinhood Chain (4663)','block_number':int(state['number'],16),'timestamp_UTC':stamp(state),'prefunded_adapter':F,'prefunded_runtime_matches_verified_Ethereum_deployment':same,'prefunded_runtime_keccak':'0x'+keccak(bytes.fromhex(pref[2:])),'gateway':G,'gateway_current_implementation_observation':raw('gateway_snapshot_implementation'),'executor':E,'executor_current_code_nonempty':len(r('executor_snapshot_code'))>2,'framework_association':'SUPPORTED Across V5 Gateway/PrefundedAdapter family, using verified source with case event/call correspondence; current code equality if true is not a case-date deployment or governance audit','evidence_files':ef(['snapshot','prefunded_snapshot_code','gateway_snapshot_code','executor_snapshot_code','gateway_snapshot_implementation','escrow_eth_metadata'])+['access/executor_eth_metadata.json','../robinhood_funding_direct_2026_10_09/access/gateway_implementation.response.txt'],'attribution_significance':'Protocol/account roles only, not broker/app account ownership, named submitter operator, private custodian or beneficiary.'})
add({'classification':'UNRESOLVED','record_type':'Role/control and complete-funding boundaries','native_prefunding_source':U,'outer_sender_fee_payer':Z,'matched_prefunded_routes':7,'matched_native_prefunding_ETH':units(sum(int(x['amount_wei']) for x in edges)),'funding_provenance':'PARTIAL / RE-ESTABLISHED for seven exact last-hop native sources; full affected-wallet chain UNRESOLVED','confirmed_account_overlap':'Same 0x427c sends eight direct bridge deposits and seven prefund transactions at sequential account nonces 10–24. This is account-level transaction-sender overlap, not identity or common ownership with 0x07ae.','fee_funding':'Outer 0x07ae pays its own zero-value transaction gas; earlier fee funding/common funder UNRESOLVED because historical balances and indexed account history were unavailable.','signature_limit':'Merkle membership and event/ABI correspondence independently validated; no standalone user authorization/signature recovery or private-key ownership inference.','provenance_limit':'Native source proven from 0x427c into per-witness adapter and through bridge. Token-sale proceeds into that pooled native balance still not reconstructed. Timing and equal token/native numbers do not repair that gap.','next_target':'Fresh Ethereum callback/native-credit reconstruction and post-bridge pooled disposal boundary','attribution_significance':'No new exchange account, private custody relationship, common operator or beneficiary. Privacy Cash unchanged; no article or extra losses.'})
assert rows[-1]['ID']=='F0538'
old=json.loads((B/'robinhood_funding_direct_2026_10_09/master_timeline_F0001_F0522.json').read_text())['rows']
(P/'ledger_F0523_F0538.json').write_text(json.dumps(rows,indent=2)+'\n');(P/'master_timeline_F0001_F0538.json').write_text(json.dumps({'notes':'Prior 522 objects unchanged. Prefund edges complete last-hop funding for seven contract-mediated routes, not affected-wallet provenance or extra loss. Privacy Cash separate.','rows':old+rows},indent=2)+'\n');(P/'funding_edges.json').write_text(json.dumps(edges,indent=2)+'\n')
