"""Derive reviewed exact-credit block from preserved evidence; no online requests."""
import datetime,decimal,hashlib,json,pathlib
P=pathlib.Path(__file__).parent;A=P/'access';D=decimal.Decimal
U='0xae06669dfd3e932476f00ea49fce82e5e63f83bf';S='0x2df1c51e09aecf9cacb7bc98cb1742757f163df7';W='0xd116117e42279dea647d45dd012c67e31e7d1a63'
def raw(n):return json.loads((A/(n+'.response.txt')).read_text())
def r(n):return raw(n)['result']
def utc(n):return datetime.datetime.fromtimestamp(n,datetime.timezone.utc).isoformat()
def save(n,d):(P/n).write_text(json.dumps(d,indent=2)+'\n')
def words(log):d=log['data'][2:];return [d[i:i+64] for i in range(0,len(d),64)]
t,q,b=r('credit_tx'),r('credit_receipt'),r('credit_block');tl,wl=q['logs'];w=words(wl);rows=[]
limit='Directed funding/service roles only; no shared-control inference, identified person, custody relationship, victim-fund allocation or ultimate beneficiary. Common protocol use, timing and similar amounts are not provenance proof.'
rows.append({'ID':'F0604','classification':'CONFIRMED','record_type':'Exact nearest preceding Arbitrum USDC credit into common funder','evidence_files':['access/credit_tx.response.txt','access/credit_receipt.response.txt','access/credit_block.response.txt','access/funder_incoming_usdc_logs.response.txt'],'details':{'chain':'Arbitrum One (42161)','transaction_hash':t['hash'],'block_number':int(b['number'],16),'timestamp_UTC':utc(int(b['timestamp'],16)),'transaction_sender':t['from'],'transaction_destination':t['to'],'token_sender':S,'token_recipient':U,'token_contract':tl['address'],'USDC':'1002.3','raw_USDC_units':str(int(tl['data'],16)),'token_log_index':int(tl['logIndex'],16),'status':'successful receipt / block inclusion reproduced','gasUsed':int(q['gasUsed'],16),'effectiveGasPrice_wei':int(q['effectiveGasPrice'],16),'network_fee_ETH':str(D(int(q['gasUsed'],16)*int(q['effectiveGasPrice'],16))/10**18),'scope_startblock':512242744,'scope_endblock':512342744,'nearest_credit_basis':'One incoming native USDC Transfer to this address returned in exact bounded block range; no timing-based allocation of later spend'},'limits':limit})
req=r('withdrawal_request_receipt')['logs'];rq=next(x for x in req if x['address']==S and x['topics'][0]=='0xcc10abf54af5c0718b10b0156dfe1e369ce3eee72423e9e86936a0082e9c5d1b');rw=words(rq);api=raw('withdrawal_user_ledger');withdraw=next(x for x in api if x['delta']['type']=='withdraw');internal=next(x for x in api if x['delta']['type']=='accountClassTransfer')
rows.append({'ID':'F0605','classification':'CONFIRMED','record_type':'Exact Hyperliquid withdrawal user/destination correspondence; request-to-finalization match','evidence_files':['access/withdrawal_request_tx.response.txt','access/withdrawal_request_receipt.response.txt','access/withdrawal_request_block.response.txt','access/withdrawal_requested_logs.response.txt','access/credit_tx.response.txt','access/credit_receipt.response.txt','access/withdrawal_user_ledger.response.txt','access/bridge_official_source.response.txt','access/sender_latest_code.response.txt'],'details':{'Hyperliquid_withdrawal_user':W,'Arbitrum_destination':U,'asset':'native Arbitrum USDC','net_USDC':'1002.3','API_fee_USDC':'1.0','withdrawal_nonce':int(w[2],16),'withdrawal_message':'0x'+w[3],'finalization_transaction_hash':t['hash'],'finalization_timestamp_UTC':utc(int(b['timestamp'],16)),'request_transaction_hash':r('withdrawal_request_tx')['hash'],'request_block':int(r('withdrawal_request_block')['number'],16),'request_timestamp_UTC':utc(int(r('withdrawal_request_block')['timestamp'],16)),'request_transaction_sender':r('withdrawal_request_tx')['from'],'finalization_transaction_sender':t['from'],'first_party_withdrawal_record':withdraw,'preceding_internal_transfer_record':internal,'internal_transfer_limit':'1003.3 USDC spot-to-perp recorded; arithmetic equals net withdrawal plus fee. It is not an external funding-source identification.','protocol_identifiers_matched':['exact Arbitrum finalization hash in account-specific Hyperliquid ledger','exact net USDC amount','exact nonce in API and RequestedWithdrawal/FinalizedWithdrawal','same indexed withdrawal user and destination in request/finalization','same 32-byte message in request/finalization and batchedFinalizeWithdrawals calldata'],'role_distinction':'Indexed withdrawal user is 0xd116, recipient is 0xae066. Neither request submitter nor finalizer is automatically account owner or beneficiary. Validator processing is not proof of a recovered user signature.','contract_type':'Hyperliquid Bridge2 contract; current nonempty runtime code and case contract-emitted event reproduced. Historical bytecode unavailable. Official repository source supplies ABI/event definitions, not independent deployed-bytecode source verification.','official_source_git_blob_sha':'2f2e98e3be5e6eccc3a24e5a8317105e220e7ccb','service_boundary':'Newly reproduced funding-side Hyperliquid withdrawal boundary; Hyperliquid service already identified elsewhere in case. Not a new exchange or custody owner.','link_to_previously_matched_account':'No evidence connecting this withdrawal to 0x3e2d81f7a5659e4760ba929ef88eed40ef6640a1 or its XMR1 balance; that boundary stays closed.'},'limits':limit})
save('ledger_F0604_F0605.json',rows);old=json.loads((P.parent/'hyperliquid_withdrawal_recheck_2026_10_10/master_timeline_F0001_F0603.json').read_text());save('master_timeline_F0001_F0605.json',{'rows':old['rows']+rows});save('credit_summary.json',{'base_commit':'582bd31cfe0d1056b347d585b436978182bc2592','latest_ID':'F0605','credit':rows[0]['details'],'withdrawal':rows[1]['details'],'upstream_case_provenance':'UNRESOLVED'})
save('SHA256SUMS.json',{str(f.relative_to(P)):hashlib.sha256(f.read_bytes()).hexdigest() for f in sorted(P.rglob('*')) if f.is_file() and '__pycache__' not in f.parts and f.name!='SHA256SUMS.json'})
