"""Finalize bounded provenance assessment using only captured data and prior ledger."""
import datetime,decimal,hashlib,json,pathlib
P=pathlib.Path(__file__).parent;A=P/'access';D=decimal.Decimal
U='0xae06669dfd3e932476f00ea49fce82e5e63f83bf';S='0x2df1c51e09aecf9cacb7bc98cb1742757f163df7';W='0xd116117e42279dea647d45dd012c67e31e7d1a63'
def raw(n):return json.loads((A/(n+'.response.txt')).read_text())
def r(n):return raw(n)['result']
def save(n,d):(P/n).write_text(json.dumps(d,indent=2)+'\n')
def event(l):return {'transaction_hash':l['transactionHash'],'block_number':int(l['blockNumber'],16),'transaction_index':int(l['transactionIndex'],16),'log_index':int(l['logIndex'],16),'source':'0x'+l['topics'][1][-40:],'destination':'0x'+l['topics'][2][-40:],'token_contract':l['address'],'USDC':str(D(int(l['data'],16))/10**6),'raw_USDC_units':str(int(l['data'],16))}
pool=[event(x) for x in r('sender_incoming_usdc_logs')];save('bounded_bridge_incoming_context.json',{'startblock':512341669,'endblock':512342669,'events':pool,'allocation':'None; shared bridge liquidity. No constituent deposit is assigned to this withdrawal. No counterparties followed.'})
prior=json.loads((P.parent/'hyperliquid_withdrawal_recheck_2026_10_10/master_timeline_F0001_F0603.json').read_text())['rows'];matches=[x['ID'] for x in prior if W in json.dumps(x).lower()];assert matches==[];save('prior_ledger_comparison.json',{'prior_public_commit':'582bd31cfe0d1056b347d585b436978182bc2592','latest_prior_ID':'F0603','withdrawal_user':W,'prior_records_mentioning_exact_withdrawal_user':matches,'previous_service_boundary_examples':['F0502','F0571','F0586'],'comparison_limit':'Same Hyperliquid bridge endpoint was known. This source account is not identified in prior ledger. Absence from ledger does not prove unrelated ownership or no lifetime case connection.'})
rows=[{'ID':'F0606','classification':'CONFIRMED','record_type':'Bounded balance/log context; allocation and state-access limitations','evidence_files':['access/funder_incoming_usdc_logs.response.txt','access/funder_outgoing_usdc_logs.response.txt','access/sender_incoming_usdc_logs.response.txt','bounded_bridge_incoming_context.json','access/withdrawal_user_preceding_ledger.response.txt','access/funder_usdc_before_request.response.txt','access/funder_usdc_after_request.response.txt','access/sender_usdc_before_credit.response.txt','access/sender_usdc_after_credit.response.txt','access/funder_usdc_before_credit.response.txt','access/sender_case_code.response.txt','access/arb_alternative_sender_balance.json','access/arb_alternative_sender_code.json'],'details':{'funder_token_log_scope':[512242744,512342744],'incoming_credits_in_scope':len(r('funder_incoming_usdc_logs')),'outgoing_debits_in_scope':len(r('funder_outgoing_usdc_logs')),'preceding_credit_USDC':'1002.3','later_Relay_request_USDC':'1002.533798','difference_USDC':'0.233798','balance_implication':'Successful USDC debit exceeds the reproduced nearest credit by 0.233798 USDC. Under standard Transfer/balance accounting, at least that much pre-existing balance is necessary; exact starting/ending balances and exclusive allocation are not established.','historical_sender_balance_context':'UNRESOLVED: eth_call before/after credit returned missing historical state, not balances. Alternate RPC attempts HTTP 400; no zero-balance claim.','historical_funder_balance_context':'UNRESOLVED: before credit and before/after Relay request state calls unavailable. No exact account reconciliation.','bridge_recent_incoming_scope':[512341669,512342669],'bridge_recent_incoming_events':len(pool),'bridge_recent_incoming_USDC_total':str(sum(D(x['USDC']) for x in pool)),'bridge_recent_incoming_context':'Direct token logs enumerate ten shared-pool credits; none assigned to the withdrawal. Receipt/UTC reconstruction of unrelated pool contributors and counterparties fan-out deliberately not performed.','source_account_preceding_ledger_scope_ms':[1791244800000,1791315607707],'source_account_preceding_ledger_records_returned':len(raw('withdrawal_user_preceding_ledger')),'scope_limit':'Empty earlier account ledger window is not lifetime absence and says nothing about prior spot trades/balance origins. No trades/fills branch opened.'},'limits':'Token logs and API responses only. Similar amounts, time proximity, funding or use of this common bridge cannot establish victim provenance or common control.'},
{'ID':'F0607','classification':'UNRESOLVED','record_type':'Case provenance and identity assessment; explicit branch closure','evidence_files':['ledger_F0604_F0605.json','prior_ledger_comparison.json','access/withdrawal_user_ledger.response.txt','access/withdrawal_user_preceding_ledger.response.txt','access/relay_credit_hash.response.txt'],'details':{'exact_credit':'CONFIRMED','source_bridge':'CONFIRMED Hyperliquid withdrawal bridge','source_account_to_destination_relationship':'CONFIRMED exact withdrawal user 0xd116117e42279dea647d45dd012c67e31e7d1a63 → destination 0xae06669dfd3e932476f00ea49fce82e5e63f83bf','victim_linked_upstream_provenance':'UNRESOLVED / not established','known_case_wallet_upstream_provenance':'UNRESOLVED / no independent upstream source match to prior case routes; prior ledger does not name withdrawal user','exclusive_USDC_allocation_to_Relay':'UNRESOLVED / credit and spend differ, historical balances unavailable','protocol_identifiers':'Hyperliquid withdrawal identifiers matched in F0605. Relay lookup by credit hash returned no requests; bridge identifier is not reused as a case Relay order match.','new_service_boundary':'Funding-side Hyperliquid withdrawal newly linked to common funder; service itself already known. No newly identified exchange/custody owner.','control_or_identity_signal':'Directed withdrawal user/destination relationship confirmed, but no recovered user signature, shared-control proof or independently identified person. Relayer/finalizer addresses are execution roles.','beneficiary':'UNRESOLVED / unchanged; destination address is not identified beneficiary','source_account_earlier_USDC_origin':'UNRESOLVED / first-party preceding ledger window empty; prior spot balance not traced','branch_status':'CLOSED — preceding Arbitrum credit reproduced / case provenance unresolved','next_concrete_lead':'None meeting case-specific evidential threshold in saved material. Prior spot-balance tracing is technically possible but not presently a demonstrated case lead; not pursued.','closed_boundaries_preserved':'Robinhood pool reconciliation, matched Hyperliquid XMR1 continuation and ten-recipient common-funder relationship remain closed. No pool donor allocation or unrelated account fan-out.'},'limits':'Closure is a scoped unresolved outcome. No independent confirmed victim/case-wallet upstream source, legal custody/beneficiary identity or common-control inference. Funding-side protocol boundary improves routing reconstruction only.'}]
save('ledger_F0606_F0607.json',rows);old=json.loads((P/'master_timeline_F0001_F0605.json').read_text());save('master_timeline_F0001_F0607.json',{'rows':old['rows']+rows});save('closure_summary.json',{'base_commit':'f6da63c30512d708b546cfbffc70d6524cfeabf6','latest_ID':'F0607','status':rows[-1]['details']})
save('SHA256SUMS.json',{str(f.relative_to(P)):hashlib.sha256(f.read_bytes()).hexdigest() for f in sorted(P.rglob('*')) if f.is_file() and '__pycache__' not in f.parts and f.name!='SHA256SUMS.json'})
