import datetime,decimal,hashlib,json,pathlib
P=pathlib.Path(__file__).parent;A=P/'access';D=decimal.Decimal
USER='0x3e2d81f7a5659e4760ba929ef88eed40ef6640a1';H='0x963c56253dedcfd5ff9f944c91eb9cb9e94d12701d9165f66a40b9aa0b4cfc1f'
def raw(n):return json.loads((A/(n+'.response.txt')).read_text())
def write(n,d):(P/n).write_text(json.dumps(d,indent=2)+'\n')
ledger=raw('ledger_0');fills=raw('fills_0');spot=raw('spot_state');perp=raw('perp_state');meta=raw('spot_meta');scope=json.loads((P/'scope.json').read_text())
gross=sum(D(x['sz']) for x in fills);fee=sum(D(x['fee']) for x in fills);cost=sum(D(x['sz'])*D(x['px']) for x in fills)
market=next(x for x in meta['universe'] if x['index']==260);tokens=[next(x for x in meta['tokens'] if x['index']==i) for i in market['tokens']]
summary={'account':USER,'deposit_hash':H,'deposit_USDC':'26823.206875','spot_internal_credit_USDC':'26823.2','fills':len(fills),'distinct_order_IDs':len(set(x['oid'] for x in fills)),'distinct_execution_hashes':len(set(x['hash'] for x in fills)),'first_fill_UTC':datetime.datetime.fromtimestamp(min(x['time'] for x in fills)/1000,datetime.timezone.utc).isoformat(),'last_fill_UTC':datetime.datetime.fromtimestamp(max(x['time'] for x in fills)/1000,datetime.timezone.utc).isoformat(),'gross_XMR1':str(gross),'XMR1_fee':str(fee),'net_XMR1':str(gross-fee),'USDC_execution_cost':str(cost),'spot_USDC_remaining':str(D('26823.2')-cost),'perp_USDC_reported':perp['marginSummary']['totalRawUsd'],'external_withdrawal_observed':False,'scope':scope,'before_deposit_balance':'UNRESOLVED: no historical pre-deposit account state obtained; first fill starts at zero XMR1 only','after_deposit_balance':'credit event observed; no historical whole-account state obtained','physical_fund_provenance':'MIXED upstream Ethereum pool; exact deposit/account link does not allocate an individual Robinhood deposit','terminal_boundary':'No verified external withdrawal/redemption; XMR1 spot holding is not native Monero receipt. Close at observed account boundary through recorded cutoff.'}
write('fills.json',fills);write('market_snapshot.json',{'market':market,'tokens':tokens});write('summary.json',summary)
rows=[]
def row(kind,evidence,details):
 rows.append({'ID':f'F{586+len(rows):04}','classification':'CONFIRMED','record_type':kind,'account':USER,'evidence_files':evidence,'details':details,'limits':'First-party API observation and saved receipt checks, not HyperCore signature/consensus or beneficiary verification. No exclusive affected-wallet allocation.'})
row('Fresh reproduction of existing deposit F0571; no new economic transfer',['access/deposit_tx.response.txt','access/deposit_receipt.response.txt','access/deposit_block.response.txt','access/arb_chain.response.txt','access/ledger_0.response.txt'],{'hash':H,'USDC':'26823.206875','chain':'Arbitrum 42161','endpoint':'0x2df1c51e09aecf9cacb7bc98cb1742757f163df7','deposit_event':ledger[0]})
row('Existing internal account-class transfer F0572 freshly reproduced',['access/ledger_0.response.txt'],{'event':ledger[1],'external_withdrawal':False})
row('Dated first-party spot market mapping',['access/spot_meta.response.txt','market_snapshot.json'],{'market_index':260,'base_token_index':404,'base_name':'XMR1','quote_token_index':0,'quote_name':'USDC','native_Monero_receipt':False})
row('28 subsequent XMR1 buy fills in matched account',['access/fills_0.response.txt','fills.json'],{k:summary[k] for k in ['fills','distinct_order_IDs','distinct_execution_hashes','first_fill_UTC','last_fill_UTC','gross_XMR1','XMR1_fee','net_XMR1','USDC_execution_cost']})
row('Dated spot balance snapshot',['access/spot_state.response.txt','access/spot_state.json'],spot)
row('Dated perpetual state and scoped funding observations',['access/perp_state.response.txt','access/perp_state.json','access/funding.response.txt'],{'state':perp,'funding_updates':raw('funding'),'perp_fills_returned':sum(not x['coin'].startswith('@') for x in fills),'limit':'No returned perp fills/funding in queried scope; not lifetime or all dex absence.'})
row('Exact account-level spot arithmetic reconciliation',['summary.json','fills.json','access/spot_state.response.txt','access/perp_state.response.txt'],{'gross_minus_token_fee_XMR1':str(gross-fee),'spot_credit_minus_cost_USDC':str(D('26823.2')-cost),'deposit_minus_spot_internal_credit_USDC':'0.006875','reported_perp_USDC':'0.006875','limit':'Difference matches reported perp residual; not assigned to a fee. Historical account state before/after deposit remains unresolved.'})
row('Scoped terminal account boundary; no external withdrawal returned',['scope.json','access/ledger_0.response.txt','access/ledger_1.response.txt','access/fills_0.response.txt','access/fills_1.response.txt','access/info_docs.response.txt'],{'ledger_event_types':[x['delta']['type'] for x in ledger],'external_withdrawal':'NOT OBSERVED in queried first-party ledger','destination_chain':None,'destination_address':None,'withdrawal_asset':None,'withdrawal_amount':None,'withdrawal_hash':None,'branch_status':'CLOSED at dated account boundary; reopen only on new concrete external event','historical_balance_status':'UNRESOLVED','service':'existing Hyperliquid; no new external service','beneficiary':'UNRESOLVED','scope':scope,'pagination':'Short pages (2 ledger events, 28 fills) followed by empty continuation pages; no cap reached. Does not establish complete lifetime history.'})
write('ledger_F0586_F0593.json',rows)
old=json.loads((P.parent/'robinhood_disposal_settlement_2026_10_09/master_timeline_F0001_F0585.json').read_text())['rows'];write('master_timeline_F0001_F0593.json',{'rows':old+rows})
