import pathlib,json,csv,decimal,datetime
P=pathlib.Path(__file__).parent;R=P/'raw_sources';V=P.parent/'frogman_research_v0_1';D=decimal.Decimal
H='69FnU8vszZSZF6DZCT6VHdsvm3DvvojDgbwqzHJ4cCFS';G='Grr9WnZdcetQywtFXog81UhqmnJyvFhb4AT3ipw44mZP';ENGINE='61DFfeTKM7trxYcPQCM78bJ794ddZprZpAwAnLiwTpYH';Z='ZesMGYmokFiEuDvNzWeMhB7jxF6eUW8c512vwSKSTNK';SIG='5fFLUqvsAJLEn1cPnypjzfKi8iioUYCnaCgR8QonKtE2U3xf6nk8RduhjURrjLP32yX1pzTT9vy9bXHXfQyNA87t';rows=[]
def add(timestamp,chain,tx,source,destination,asset,amount,action,protocol,authority,prov,cl,record,notes):
 rows.append({'ID':f'F{103+len(rows):04d}','timestamp':timestamp,'chain':chain,'tx/signature':tx,'source':source,'destination':destination,'asset':asset,'amount':amount,'USD value if available':'','action':action,'protocol':protocol,'signer/authority if known':authority,'provenance status':prov,'classification':cl,'source_record':record,'notes':notes,'record_type':'evidence enrichment; not an additional transfer'})
time='2026-10-06T20:35:41Z'
add(time,'Solana mainnet',SIG,H,G,'','', 'program identity established',ENGINE,'','mixed','CONFIRMED','raw_sources/jupiter_order_engine_idl.json','Jupiter first-party documentation and IDL identify mainnet order engine; no claim of human operator.')
add(time,'Solana mainnet',SIG,H,G,'','', 'wire signer correction',ENGINE,G+';'+H,'mixed','CONFIRMED','raw_sources/conversion_base64.response.json','Two wire signatures verify with OpenSSL; supersedes v0.1 non-signer assertion. Frozen jsonParsed source retained.')
add(time,'Solana mainnet',SIG,H,'8Ti6AMEkfZnFjKTa3kJw9mNsyjgKC5vwCxViqgViMj9S','USDC','7859.975842','counterparty inventory settlement',ENGINE,G+';'+H,'mixed','CONFIRMED','../frogman_research_v0_1/raw_transactions/'+SIG+'.json','Counterparty USDC balance 78893.785242 -> 86753.761084; counterpart account owner Grr9; this is not another USDC transfer beyond v0.1 ledger.')
add(time,'Solana mainnet',SIG,'Bukt1ztP1AetQPdfHKUjFp7cVJPFusCNi98bvZcL7Ug5',H,'SOL/WSOL','64.925550449','output inventory and unwrap analysis',ENGINE,G+';'+H,'mixed counterparty inventory; deterministic paired execution','CONFIRMED','../frogman_research_v0_1/raw_transactions/'+SIG+'.json','Grr9 WSOL inventory 754.887798786 -> 689.962248337; temporary account funded, closed, then native SOL sent to H. No beneficial-owner inference.')
req=json.loads((R/'mint_zes.request.json').read_text());snapshot=req['requested_at_UTC']
add(snapshot,'Solana mainnet','',Z,'','basis points','100','current mint configuration observation','Token-2022','','intact snapshot; historical state not obtained','CONFIRMED','raw_sources/mint_zes.response.json','Both older/newer fee settings are 100 bps; not a historical state proof. Current on-chain metadata names Just a Backpack.')
add('2026-10-06T20:15:05Z','Solana mainnet','3D3a45d4HYvvNfD4h5o4YSMc1PpW8QFpx4rxrCVvTPMN3wZJb2KTBfC3FncLJGhb7dUVYvCmXuJC8J89ppMbLG5f',Z,H,'Just a Backpack','160314.105600','historical difference explanation','Token-2022','','intact debit-credit observation; fee cause supported','SUPPORTED','raw_sources/mint_zes.response.json','Exact 1% difference is CONFIRMED in frozen receipt; transferFeeConfig explanation SUPPORTED by current mint, not promoted to historical CONFIRMED without historic extension state.')
add('2026-10-06T20:18:14Z/2026-10-06T20:23:43Z','Solana mainnet','four BP disposal signatures in sale_reconciliation_v0.2.csv',H,'routing recipients in frozen ledger','SOL/WSOL','6.686352013','routing deduction reconciliation','','H','mixed native balance; deterministic accounting','CONFIRMED','accounting_reconciliation_v0.2.json','Four gross receipts minus native increases minus network fees. Deductions 3.488714663 and 3.197637350; count original wallet debits once, not forwarded fees.')
add('2026-10-06T21:00:54Z','Solana mainnet','3f9ABQgo1xe4gVrDYxFJTSVvfeEz6pucS2ARDypLis6cMDDiT8X789Jf9ipR71n8ZjbvnAu1e9vQHquFwz21DWYm',H,'pool/fees/accounts/remaining','SOL','13240.996153263','native wallet accounting reconciliation','','H','mixed inflows; pool withdrawal linkage broken','CONFIRMED','accounting_reconciliation_v0.2.json','Deposits13240.973780900 + network0.002050000 + new-account allocations0.013919200 + remaining0.006403163; residual0.000000000. Does not relabel all lamports as exclusively case-derived.')
for a in ['0x14AA2A71dbb5eF87b81F92205E2699AA4aa65794','0x427C4b37de0714821B09C4FC655a713AbbCfbA83']:
 key='bsc_nonce_'+a;req=json.loads((R/(key+'.request.json')).read_text());res=json.loads((R/(key+'.response.json')).read_text()).get('result');add(req['requested_at_UTC'],'BNB Smart Chain (provider endpoint; see chain ID record)','',a,'','transaction count',str(int(res,16)),'current nonce observation','','','incident provenance UNRESOLVED','CONFIRMED','raw_sources/'+key+'.response.json','Nonzero nonce establishes chain activity only; does not identify incident transaction or reproduce EVM exit claims.')
with (P/'transaction_ledger_v0.2.csv').open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=rows[0]);w.writeheader();w.writerows(rows)
(P/'wallet_graph_v0.2.json').write_text(json.dumps({'version':'v0.2','frozen_ledger':'F0001-F0102 unchanged','edges':[{'source':H,'destination':G,'asset':'USDC','amount':'7859.975842','signature':SIG,'classification':'CONFIRMED','provenance':'mixed','relationship':'paired RFQ settlement; source instruction unchanged'},{'source':G,'destination':H,'asset':'SOL/WSOL','amount':'64.925550449','signature':SIG,'classification':'CONFIRMED','provenance':'deterministic paired exchange; output from existing counterparty inventory','relationship':'temporary WSOL account unwrap and native payment'},{'source':H,'destination':G,'signature':SIG,'classification':'CONFIRMED','relationship':'both keys cryptographically sign same execution; no shared human ownership established'}]},indent=2)+'\n')
wallets=[{'address':G,'chain':'Solana','role':'RFQ settlement counterparty; signer and fee payer','classification':'CONFIRMED','control_evidence':'One transaction co-signed with H; inventory exchange reproduced','identity':'NOT ESTABLISHED','notes':'Registered market-maker identity not independently established; recent 1000-signature page did not reach incident.'},{'address':H,'chain':'Solana','role':'case receiving wallet; RFQ taker and verified co-signer','classification':'CONFIRMED','control_evidence':'Wire Ed25519 signature verifies; v0.1 parsed flag corrected','identity':'NOT ESTABLISHED','notes':'Operational pairing does not establish shared beneficial ownership.'},{'address':ENGINE,'chain':'Solana','role':'Jupiter order engine program','classification':'CONFIRMED','control_evidence':'First-party mainnet ID plus incident invocation','identity':'protocol, not human','notes':'Current source/interface matched; historic deployed build equivalence not verified.'}]
with (P/'wallet_entity_update_v0.2.csv').open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=wallets[0]);w.writeheader();w.writerows(wallets)
print('new ledger IDs',rows[0]['ID'],rows[-1]['ID'])
