import json,csv,pathlib,decimal,datetime
P=pathlib.Path(__file__).parent;R=P/'raw_sources';D=decimal.Decimal;A='0x427c4b37de0714821b09c4fc655a713abbcfba83'
ts=json.loads((R/'eth_history_combined.json').read_text())['items'];outs=sorted([t for t in ts if t['from']['hash'].lower()==A],key=lambda x:(x['block_number'],x['position'] if 'position'in x else 0));rows=[]
for t in outs:
 h=t['hash'];tx=json.loads((R/('eth_getTransactionByHash_'+h+'.response.json')).read_text())['result'];receipt=json.loads((R/('eth_getTransactionReceipt_'+h+'.response.json')).read_text())['result'];block=json.loads((R/('eth_block_'+str(t['block_number'])+'.response.json')).read_text())['result']
 assert tx['hash']==h==receipt['transactionHash'];assert tx['blockHash']==receipt['blockHash']==block['hash'];assert h in block['transactions'];assert tx['from']==A;assert int(receipt['status'],16)==1;assert int(tx['value'],16)==int(t['value'])
 rows.append({'ID':f'F{113+len(rows):04d}','timestamp':datetime.datetime.fromtimestamp(int(block['timestamp'],16),datetime.timezone.utc).isoformat().replace('+00:00','Z'),'chain':'Ethereum mainnet (1)','tx/signature':h,'source':tx['from'],'destination':tx['to'],'asset':'ETH','amount':format(D(int(tx['value'],16))/10**18,'f'),'USD value if available':'','action':'native ETH transfer','protocol':'UNRESOLVED','signer/authority if known':tx['from'],'provenance status':'intact transfer; linkage to affected wallet UNRESOLVED; wallet mixes inflows','classification':'CONFIRMED','source_record':'raw_sources/eth_getTransactionByHash_'+h+'.response.json','notes':'Receipt and block hash/inclusion independently cross-checked. Receiving address role does not establish identity. Fee excludes transferred amount.','network_fee_ETH':format(D(int(receipt['gasUsed'],16)*int(receipt['effectiveGasPrice'],16))/10**18,'f'),'nonce':int(tx['nonce'],16),'record_type':'fund transfer'})
assert [r['nonce'] for r in rows]==list(range(15))
with (P/'evm_transaction_ledger_v0.2.csv').open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=rows[0]);w.writeheader();w.writerows(rows)
s={'confirmed_outgoing_transactions':len(rows),'ledger_ID_range':'F0113-F0127','outgoing_ETH':format(sum(D(r['amount']) for r in rows),'f'),'network_fees_ETH':format(sum(D(r['network_fee_ETH']) for r in rows),'f'),'current_balance_ETH':format(D(int(json.loads((R/'eth_current_eth_getBalance.response.json').read_text())['result'],16))/10**18,'f'),'balance_snapshot_request_record':'raw_sources/eth_current_eth_getBalance.request.json','scope':'All 15 outgoing Ethereum nonces 0 through 14 reproduced; affected-wallet source and cross-chain destinations not yet reproduced.'}
(P/'evm_summary_v0.2.json').write_text(json.dumps(s,indent=2)+'\n');print(s)
