import pathlib,csv,json,decimal
P=pathlib.Path(__file__).parent;V=P.parent/'frogman_research_v0_1';D=decimal.Decimal
sales=list(csv.DictReader((V/'asset_disposal.csv').open()));bp=[r for r in sales if r['asset_decrease'].startswith('BPxx')];z=next(r for r in sales if r['asset_decrease'].startswith('Zes'));rfq=next(r for r in sales if r['asset_decrease'].startswith('EPj'));deposits=list(csv.DictReader((V/'privacy_cash_deposits.csv').open()));rows=[]
for r in bp+[z]:
 gross=D(r['WSOL_gross_receipts_SOL']);net=D(r['native_balance_change_SOL']);fee=D(r['network_fee_SOL']);rows.append({'signature':r['signature'],'timestamp':r['timestamp'],'asset_decrease':r['asset_decrease'],'gross_WSOL_receipts_SOL':str(gross),'native_balance_increase_SOL':str(net),'network_fee_SOL':str(fee),'gross_less_native_less_network_SOL':str(gross-net-fee),'interpretation':'Routing deduction where nonzero; confirm recipient in original instruction ledger. Intermediate forwarding is not a second fee.'})
with (P/'sale_reconciliation_v0.2.csv').open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=rows[0]);w.writeheader();w.writerows(rows)
bpnet=sum(D(r['native_balance_change_SOL']) for r in bp);znet=D(z['native_balance_change_SOL']);rfqnet=D(rfq['native_balance_change_SOL']);direct=D('0.293808325');dust=D('0.000001000');pool=sum(D(r['amount_SOL']) for r in deposits);fee=sum(D(r['fee_SOL']) for r in deposits);rent=sum(D(r['other_balance_cost_SOL']) for r in deposits);remaining=D('0.006403163');inflow=bpnet+znet+rfqnet+direct+dust;outflow=pool+fee+rent+remaining
summary={'BP_gross_WSOL_receipts_SOL':str(sum(D(r['WSOL_gross_receipts_SOL']) for r in bp)),'BP_native_balance_increases_SOL':str(bpnet),'BP_network_fees_SOL':str(sum(D(r['network_fee_SOL']) for r in bp)),'BP_routing_deductions_SOL':str(sum(D(r['gross_less_native_less_network_SOL']) for r in rows[:4])),'Zes_native_balance_increase_SOL':str(znet),'USDC_RFQ_native_balance_increase_SOL':str(rfqnet),'initial_case_SOL_transfer':str(direct),'third_party_native_SOL':str(dust),'receiving_wallet_native_inflow_total_SOL':str(inflow),'Privacy_Cash_deposits_SOL':str(pool),'deposit_network_fees_SOL':str(fee),'deposit_new_account_allocations_SOL':str(rent),'final_incident_receipt_balance_SOL':str(remaining),'accounting_residual_SOL':str(inflow-outflow),'third_party_USDC':str(D('7859.975842')-D('7859.974642'))}
assert inflow==outflow;assert summary['BP_routing_deductions_SOL']=='6.686352013'
(P/'accounting_reconciliation_v0.2.json').write_text(json.dumps(summary,indent=2)+'\n');print(json.dumps(summary,indent=2))
