import collections,datetime,decimal,hashlib,json,pathlib
P=pathlib.Path(__file__).parent;A=P/'access';D=decimal.Decimal
U='0x18dd3c14e34c1bc379f7538068c59160d9f68e25';F='0xae06669dfd3e932476f00ea49fce82e5e63f83bf'
def raw(n):return json.loads((A/(n+'.response.txt')).read_text())
def r(n):return raw(n)['result']
def utc(n):return datetime.datetime.fromtimestamp(n,datetime.timezone.utc).isoformat()
def eth(n):return format(D(n)/10**18,'f')
def save(n,d): (P/n).write_text(json.dumps(d,indent=2)+'\n')
def edge(n):
 t,q,b=r(n+'_tx'),r(n+'_receipt'),r(n+'_block');return dict(transaction_hash=t['hash'],source=t['from'],destination=t['to'],wei=str(int(t['value'],16)),ETH=eth(int(t['value'],16)),block=int(b['number'],16),timestamp_UTC=utc(int(b['timestamp'],16)),nonce=int(t['nonce'],16),gasUsed=int(q['gasUsed'],16),effectiveGasPrice_wei=int(q['effectiveGasPrice'],16),gas_ETH=eth(int(q['gasUsed'],16)*int(q['effectiveGasPrice'],16)),input=t['input'])
h=raw('ordinary_history')['result'];o=[x for x in h if x['from'].lower()==U];i=[x for x in h if x['to'].lower()==U];b=r('snapshot_block');req=raw('relay_case_hash')['requests'][0]
counts=collections.Counter(x['to'].lower() for x in o);save('counterparty_counts.json',{'scope':'Ethereum blocks 26135406–26135606 only; explorer enumeration, not counterparties attribution','outgoing':dict(sorted(counts.items())),'incoming':dict(collections.Counter(x['from'].lower() for x in i))})
limit='No person, custody relationship, common control, victim-fund provenance or ultimate beneficiary is identified. Service participation is distinct from ownership. No allocation to any individual Robinhood deposit.'
rows=[]
def row(ID,typ,files,d,limits=limit):rows.append(dict(ID=ID,classification='CONFIRMED',record_type=typ,evidence_files=files,details=d,limits=limits))
row('F0598','Dated funding sender EOA/code status and nonce snapshot',['access/case_code.response.txt','access/snapshot_code.response.txt','access/snapshot_nonce.response.txt','access/snapshot_balance.response.txt','access/snapshot_block.response.txt','access/metadata.response.txt'],dict(address=U,classification='funded EOA; empty code at case block and snapshot; not a deployed contract',case_block=26135506,snapshot_block=int(b['number'],16),snapshot_UTC=utc(int(b['timestamp'],16)),snapshot_outgoing_nonce=int(r('snapshot_nonce'),16),snapshot_balance_ETH=eth(int(r('snapshot_balance'),16)),deployment_metadata='Not applicable to empty-code EOA; no creation hash reported',lifetime_total_including_incoming='UNRESOLVED / not enumerated; nonce counts sent transactions only',first_lifetime_funding='UNRESOLVED / not examined'))
row('F0599','Bounded sender transaction pattern independently cross-checked with nonce change',['access/ordinary_history.response.txt','access/internal_history.response.txt','access/nonce_before.response.txt','access/nonce_after.response.txt','counterparty_counts.json'],dict(startblock=26135406,endblock=26135606,ordinary_records=len(h),outgoing_records=len(o),incoming_records=len(i),unique_outgoing_counterparties=len(counts),outgoing_nonce_min=min(int(x['nonce']) for x in o),outgoing_nonce_max=max(int(x['nonce']) for x in o),nonce_delta=int(r('nonce_after'),16)-int(r('nonce_before'),16),outgoing_32_byte_calldata=sum(len(x['input'])==66 for x in o),most_repeated_destination=counts.most_common(1)[0],internal_records_returned=len(raw('internal_history')['result']),scope_completeness='179 records below 1000 cap; contiguous 178 outgoing nonces match RPC delta; internal explorer completeness not independently established',fee_funding='Sender pays reproduced transactions gas; no dedicated fee-funder relationship established; repeated transfers alone do not imply common control'))
row('F0600','Exact Relay execution correspondence independently establishes service role',['access/relay_case_hash.response.txt','access/relay_case_order.response.txt','access/relay_api_documentation.response.txt','access/case_tx.response.txt','access/case_receipt.response.txt','access/case_block.response.txt','access/explorer_label.response.txt'],dict(address=U,service_role='Relay Ethereum destination-fill execution EOA for this exact order; explorer Solver label secondary only',request_id=req['id'],order_id=req['protocol']['orderId'],status=req['status'],destination_fill=edge('case'),origin_chainId=42161,destination_chainId=1,protocol_solver=req['protocol']['solver'],role_distinction='API protocol.solver is 0xf70da97812cb96acdf810712aa562db8dfa3dbef on Base; 0x18dd is the Ethereum fill transaction sender. Do not equate these roles or infer identical key ownership.',service_attribution='CONFIRMED at transaction execution level by first-party order/hash record and matching chain receipt; legal operator/custody identity UNRESOLVED',api_user=req['user'],api_user_limit='API user field is a routing contract here, not a person; underlying origin transaction sender checked in F0601',referrer=req.get('referrer'),referrer_limit='lifi is API-reported integration metadata only; no new LI.FI branch opened'))
origin=r('origin_tx');q=r('origin_receipt');logs=q['logs'];transfers=[dict(token=x['address'],source='0x'+x['topics'][1][-40:],destination='0x'+x['topics'][2][-40:],raw_amount=str(int(x['data'],16)),logIndex=int(x['logIndex'],16)) for x in logs if x['topics'][0]=='0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'];save('origin_token_edges.json',transfers)
row('F0601','Exact Arbitrum origin deposit and Ethereum fulfillment of funder own request',['access/origin_tx.response.txt','access/origin_receipt.response.txt','access/origin_block.response.txt','access/relay_case_hash.response.txt','origin_token_edges.json'],dict(transaction_hash=origin['hash'],chainId=42161,transaction_sender=origin['from'],transaction_destination=origin['to'],origin_block=int(origin['blockNumber'],16),timestamp_UTC=utc(int(r('origin_block')['timestamp'],16)),asset='Arbitrum native USDC 0xaf88d065e77c8cc2239327c5edb3a432268e5831',USDC='1002.533798',token_edges=transfers,depository='0x4cd00e387622c35bddb9b4c962c136462338bc31',order_id=req['protocol']['orderId'],ethereum_ETH_received='0.372051536035073867',funding_interpretation='The existing inbound ETH edge is a service fill for this same-address cross-chain request, not independent evidence of a third-party benefactor',control_signal='Origin transaction records 0xae066 as sender and Ethereum order recipient is same address; no evidence linking its controller to ten recipients or affected/root wallets',pre_origin_USDC_provenance='UNRESOLVED / not traced; no victim linkage',first_relevant_event='2026-10-06T19:44:15Z Arbitrum origin; Ethereum fill 19:44:23Z; first lifetime funding not established'))
row('F0602','One nearby inbound replenishment and explicit funding-sender closure',['access/replenishment_tx.response.txt','access/replenishment_receipt.response.txt','access/replenishment_block.response.txt','access/relay_case_hash.response.txt','access/ordinary_history.response.txt'],dict(replenishment=edge('replenishment'),relationship='Inbound from address also named by first-party API as protocol solver; native receipt reproduced. Replenishment occurs after case fill, so cannot fund that earlier fill directly.',attribution='Relay destination-fill execution EOA; exchange/custody/treasury ownership UNRESOLVED',control_or_identity_signal='No independent person or common-control signal. A recorded origin sender is a transaction role, not beneficiary identity.',beneficiary='UNRESOLVED / unchanged',branch_status='CLOSED at confirmed funding/order execution relationship; legal identity unresolved',new_lead='If pursued in a separately authorized bounded task: identify provenance of the exact 1002.533798 USDC held by 0xae066 on Arbitrum before origin tx; stop if prior credit cannot be independently linked. No counterparties fan-out undertaken here.',exhausted='Label-only attribution and timing/amount/funding-based common-control inference; Robinhood reconciliation and dated Hyperliquid XMR1 boundary stay closed'))
save('ledger_F0598_F0602.json',rows)
old=json.loads((P.parent/'common_funder_bounded_2026_10_10/master_timeline_F0001_F0597.json').read_text());save('master_timeline_F0001_F0602.json',{**old,'rows':old['rows']+rows})
save('summary.json',{'base_commit':'384267de66c4cb2585d097345a29f1672ff4d85e','latest_ID':'F0602','service_attribution':rows[2]['details'],'funding_origin':rows[3]['details'],'closure':rows[4]['details']})
if __name__=='__main__':
 save('SHA256SUMS.json',{str(f.relative_to(P)):hashlib.sha256(f.read_bytes()).hexdigest() for f in sorted(P.rglob('*')) if f.is_file() and '__pycache__' not in f.parts and f.name!='SHA256SUMS.json'})
