import datetime,decimal,json,pathlib,re,sys
P=pathlib.Path(__file__).parent;B=P.parent;A=P/'access';D=B/'robinhood_disposal_2026_10_09';M=B/'mayan_verification_2026_10_09'
sys.path.insert(0,str(M));from keccak_utils import keccak
U='0x427c4b37de0714821b09c4fc655a713abbcfba83';V='0x3e2d81f7a5659e4760ba929ef88eed40ef6640a1';F='0xae06669dfd3e932476f00ea49fce82e5e63f83bf';L='0x1231deb6f5749ef6ce6943a275a1d3e7486f4eae';USDC='0xaf88d065e77c8cc2239327c5edb3a432268e5831';HL='0x2df1c51e09aecf9cacb7bc98cb1742757f163df7'
def raw(n):return json.loads((A/(n+'.response.txt')).read_text())
def r(n):return raw(n)['result']
def dr(n):return json.loads((D/'access'/(n+'.response.txt')).read_text())['result']
def ef(*n):return ['access/'+x+'.response.txt' for x in n]
def units(n):return format(decimal.Decimal(n)/10**18,'f')
def stamp(b):return datetime.datetime.fromtimestamp(int(b['timestamp'],16),datetime.timezone.utc).isoformat()
def calls(t):
 yield t
 for x in t.get('calls',[]):yield from calls(x)
def dump(n,d):(P/n).write_text(json.dumps(d,indent=2)+'\n')
old=json.loads((D/'master_timeline_F0001_F0552.json').read_text())['rows'];rows=[]
def add(d):d={'ID':f'F{553+len(rows):04}',**d};rows.append(d);return d
add({'classification':'CONFIRMED','record_type':'Append-only checkpoint deduplication and classification clarification','clarifications':{'F0548':'Same transaction already recorded as F0179: fresh reproduction/enrichment, not a new economic edge.','F0550':'Same LI.FI input already recorded as F0180 and Mayan origin F0477: enrichment, not a new route.','F0551':'Transaction-specific API lead in that block did not independently reconstruct destination there; prior F0477–F0479 already CONFIRMED this exact Mayan order. Global route remains CONFIRMED.','F0552':'Independent destination settlement was a block-local target already resolved in prior checkpoint; no global downgrade.','F0549':'Supplemental funding into second EOA is distinct, and is independently examined here.'},'existing_Mayan_total':'Three routes, 34.75 ETH to 92468.737932 USDC unchanged','attribution_significance':'No old object is rewritten; previous-confirmation chronology retained. These duplicate reproductions are not additional edges, routes or losses.','evidence_files':['../mayan_verification_2026_10_09/transaction_ledger_F0471_F0480.json','../robinhood_disposal_2026_10_09/ledger_F0539_F0552.json']})
ordinary=[]
for p in sorted(A.glob('routing_transactions*.response.txt')):ordinary+=json.loads(p.read_text())['items']
ordinary=[x for x in ordinary if '2026-10-06T20:00'<x['timestamp']<'2026-10-07T02:19'];internal=[x for x in raw('routing_internal-transactions')['items'] if '2026-10-06T20:00'<x['timestamp']<'2026-10-07T02:19']
inbounds=[];events=[];out=[]
rh=json.loads((B/'robinhood_linkage_2026_10_09/cross_chain_edges.json').read_text());rhmap={x['destination_transaction']:x for x in rh};seven={x['destination_transaction'] for x in rh[8:]}
for x in ordinary:
 h=x['hash'];t=r(h+'_tx');q=r(h+'_receipt');b=r('block_'+t['blockNumber']);bn=int(t['blockNumber'],16);ix=int(t['transactionIndex'],16)
 if t['from']==U:out.append((t,q,b));events.append((bn,ix,1,{'kind':'out','tx':h,'amount':int(t['value'],16),'fee':int(q['gasUsed'],16)*int(q['effectiveGasPrice'],16)}))
 else:
  assert t['to']==U;credit={'source_wallet':t['from'],'destination_wallet':U,'transaction_hash':h,'asset':'native ETH','amount_wei':str(int(t['value'],16)),'block_number':bn,'timestamp_UTC':stamp(b),'record_type':'ordinary credit','upstream_provenance':'UNRESOLVED / case-unassigned; no ownership inferred','evidence_files':ef(h+'_tx',h+'_receipt','block_'+t['blockNumber'])};inbounds.append(credit);events.append((bn,ix,0,{'kind':'in','tx':h,'amount':int(t['value'],16),'rh15':False,'seven':False}))
for x in internal:
 h=x['transaction_hash'];t=r(h+'_tx');q=r(h+'_receipt');b=r('block_'+t['blockNumber']);tr=r(h+'_trace');n=int(x['value']);matches=[v for v in calls(tr) if v.get('from','').lower()==x['from']['hash'].lower() and v.get('to','').lower()==U and int(v.get('value','0x0'),16)==n];assert len(matches)==1 and not any(v.get('error') for v in calls(tr))
 credit={'source_wallet':matches[0]['from'],'destination_wallet':U,'transaction_hash':h,'asset':'native ETH','amount_wei':str(n),'block_number':int(t['blockNumber'],16),'timestamp_UTC':stamp(b),'record_type':'native execution credit','matched_call':matches[0],'existing_Robinhood_edge':rhmap[h]['ID'] if h in rhmap else None,'upstream_provenance':'Known Robinhood bridge credit; affected-wallet upstream unresolved' if h in rhmap else 'Separate protocol/dust credit; no origin-chain claim made here','evidence_files':ef(h+'_tx',h+'_receipt',h+'_trace','block_'+t['blockNumber'])};inbounds.append(credit);events.append((int(t['blockNumber'],16),int(t['transactionIndex'],16),0,{'kind':'in','tx':h,'amount':n,'rh15':h in rhmap,'seven':h in seven}))
bal=int(r('routing_pre_initial_balance'),16);assert bal==0;lo={'seven':0,'rh15':0};hi={'seven':0,'rh15':0};account=[];bounds={}
for bn,ix,_,e in sorted(events,key=lambda z:z[:3]):
 before=bal
 if e['kind']=='in':
  bal+=e['amount']
  for group in lo:
   if e[group]:lo[group]+=e['amount'];hi[group]+=e['amount']
 else:
  bounds[e['tx']]={group:{'minimum_group_principal_wei':str(max(0,lo[group]-(before-e['amount']))),'maximum_group_principal_wei':str(min(e['amount'],hi[group])),'minimum_group_balance_before_wei':str(lo[group]),'maximum_group_balance_before_wei':str(hi[group])} for group in lo};bal-=e['amount']+e['fee']
  for group in lo:lo[group]=max(0,lo[group]-e['amount']-e['fee']);hi[group]=min(hi[group],bal)
 assert bal>=0;account.append({'block_number':bn,'transaction_index':ix,**e,'balance_before_wei':str(before),'balance_after_wei':str(bal)})
totalin=sum(int(x['amount_wei']) for x in inbounds);totalout=sum(int(t['value'],16) for t,q,b in out);fees=sum(int(q['gasUsed'],16)*int(q['effectiveGasPrice'],16) for t,q,b in out);terminal='0x204c2bf7375b0d44cc648f630a09a9c32e93fe8cedc416f6587012c2afa7cc99';assert bal==int(r(terminal+'_post_balance'),16) and totalin-totalout-fees==bal
summary={'classification':'CONFIRMED','record_type':'Scoped native pool reconciliation, not complete affected-wallet provenance','routing_wallet':U,'scope_UTC':['2026-10-06T20:19:35Z','2026-10-07T02:18:11Z'],'prior_balance_wei':'0','ordinary_inbound_count':sum(x['record_type']=='ordinary credit' for x in inbounds),'internal_inbound_count':len(internal),'native_inflow_wei':str(totalin),'native_inflow_ETH':units(totalin),'native_outflow_count':len(out),'native_principal_out_wei':str(totalout),'native_principal_out_ETH':units(totalout),'wallet_paid_gas_wei':str(fees),'wallet_paid_gas_ETH':units(fees),'end_balance_wei':str(bal),'end_balance_ETH':units(bal),'residual_wei':'0','funding_provenance':'MIXED / pooled; affected-wallet origin unresolved','inbound_edges':inbounds,'indexed_history_pagination':'Two ordinary pages and one internal page exhausted; RPC receipts/traces/blocks and end balance independently reconcile scope. No assertion about later or every lifetime event.','evidence_files':ef('routing_transactions','routing_transactions_page_1','routing_internal-transactions','routing_pre_initial_balance',terminal+'_post_balance'),'attribution_significance':'Balance accounting closes scoped native inventory. Tiny distinct-address credits are case-unassigned, not owner evidence. Complete Robinhood native origin and individual fill attribution remain unresolved.'};add(summary)
oldnative=[x for x in old if x.get('record_type')=='fund transfer' and x.get('asset')=='ETH' and 113<=int(x['ID'][1:])<=180]
for t,q,b in sorted(out,key=lambda z:int(z[0]['nonce'],16)):
 h=t['hash'];o=next(x for x in oldnative if x['tx/signature']==h);bd=bounds[h]
 add({'classification':'CONFIRMED','record_type':'Routing-wallet outflow fresh reproduction / existing edge enrichment','existing_ID':o['ID'],'transaction_hash':h,'chain':'Ethereum (1)','source_wallet':U,'destination_wallet':t['to'],'asset':'native ETH','amount_wei':str(int(t['value'],16)),'amount_ETH':units(int(t['value'],16)),'block_number':int(t['blockNumber'],16),'timestamp_UTC':stamp(b),'sender_nonce':int(t['nonce'],16),'status':'success','destination_account_type':'EOA at case block' if r(h+'_recipient_code')=='0x' else 'Contract/code-bearing account','recipient_case_code':r(h+'_recipient_code'),'prior_block_balance_wei':str(int(r(h+'_pre_balance'),16)),'post_block_balance_wei':str(int(r(h+'_post_balance'),16)),'network_fee_wei':str(int(q['gasUsed'],16)*int(q['effectiveGasPrice'],16)),'funding_provenance':'MIXED routing-wallet boundary; individual seven-fill allocation UNRESOLVED','group_allocation_bounds':bd,'bound_limitation':'Conservative lower/upper bounds in the independently reconciled native account ledger. Seven means seven contract-mediated Robinhood credits; rh15 means all 15 known Robinhood credits. Positive rh15 lower bound is not a specific route ID assignment, ownership, or affected-wallet provenance. Fees allowed to consume either group.','evidence_files':ef(h+'_tx',h+'_receipt','block_'+t['blockNumber'],h+'_pre_balance',h+'_post_balance',h+'_recipient_code'),'attribution_significance':'Same signed-account nonce sequence 0–14. Existing outgoing economic edge not counted again.'})
# This route was already CONFIRMED at F0477–F0479. Independently refresh exact settlement.
d=raw('mayan_status');legacy=next(x for x in json.loads((M/'cross_chain_edges.json').read_text()) if x['source_transaction']==d['sourceTxHash']);dt=r('destination_tx');dq=r('destination_receipt');db=r('destination_block');topic=lambda s:'0x'+keccak(s.encode());created=next(x for x in dr('router_receipt')['logs'] if x['address']==legacy['mayan_source_contract'] and x['topics'][0]==topic('OrderCreated(bytes32)') and x['data']==d['orderHash']);filled=next(x for x in dq['logs'] if x['address']==legacy['mayan_destination_contract'] and x['topics'][0]==topic('OrderFulfilled(bytes32,uint64,uint256)') and x['data'][2:66]==d['orderHash'][2:]);paid=next(x for x in dq['logs'] if x['address']==USDC and x['topics'][1][-40:]==legacy['mayan_destination_contract'][2:] and x['topics'][2][-40:]==V[2:] and int(x['data'],16)==int(d['toAmount64']));assert int(filled['data'][130:194],16)==int(d['toAmount64']) and dt['hash']==legacy['destination_transaction']==d['fulfillTxHash'] and d['orderHash']==legacy['order_hash']
add({'classification':'CONFIRMED','record_type':'Previously confirmed LI.FI/Mayan route settlement fresh reproduction','existing_IDs':['F0180','F0477','F0478','F0479'],'source_transaction':d['sourceTxHash'],'source_wallet':V,'outer_router':L,'underlying_protocol':'Mayan Swift V2','source_contract':legacy['mayan_source_contract'],'destination_contract':legacy['mayan_destination_contract'],'order_hash':d['orderHash'],'order_id':d['orderId'],'lifi_transaction_id':raw('mayan_status')['meta']['consumer']+'; exact LI.FI ID in prior F0551','input_asset':'ETH locked as WETH','input_amount':'10.251','destination_chain':'Arbitrum One (42161)','destination_transaction':dt['hash'],'destination_wallet':V,'output_asset':'USDC','output_amount':'26823.206875','output_raw':d['toAmount64'],'destination_block':int(db['number'],16),'destination_timestamp_UTC':stamp(db),'status':'success','source_order_event':created,'destination_order_event':filled,'destination_transfer_event':paid,'prior_USDC_balance_raw':str(int(r('destination_pre_balance'),16)),'post_settlement_USDC_balance_raw':str(int(r('destination_post_balance'),16)),'destination_account_type':'EOA at case block','driver_fulfiller':dt['from'],'fees':legacy['fees'],'fee_note':'Prior decoded zero protocol/referrer bps preserved. API fees and cancellation/refund parameters are not newly claimed successful-route deductions; no market spread asserted.','prior_Wormhole_unlock_reference':'Existing F0480 / Mayan wormhole_batch_correspondence.json; same order batch index 1, not new VAA research','evidence_files':ef('mayan_status','destination_tx','destination_receipt','destination_block','destination_pre_balance','destination_post_balance','destination_code')+['../robinhood_disposal_2026_10_09/access/router_receipt.response.txt','../mayan_verification_2026_10_09/cross_chain_edges.json'],'attribution_significance':'Existing route remains confirmed. Complete source-to-destination settlement, not new bridge volume, custody or beneficiary.'})
rows[-1]['lifi_transaction_id']=json.loads((D/'access/router_lifi_status.response.txt').read_text())['transactionId']
ct=r('credit_tx');cq=r('credit_receipt');cb=r('credit_block');credit=next(x for x in cq['logs'] if x['address']==USDC and x['topics'][1][-40:]==V[2:] and x['topics'][2][-40:]==HL[2:]);api=raw('hyperliquid_credit');deposit=next(x for x in api if x['hash']==ct['hash'] and x['delta']['type']=='deposit');assert int(credit['data'],16)==int(d['toAmount64']) and decimal.Decimal(deposit['delta']['usdc'])*10**6==int(credit['data'],16)
add({'classification':'CONFIRMED','record_type':'New exact USDC onward transfer / Hyperliquid account credit linkage','chain':'Arbitrum One (42161)','transaction_hash':ct['hash'],'source_wallet':V,'destination_contract':HL,'asset':'USDC','amount':'26823.206875','amount_raw':str(int(credit['data'],16)),'block_number':int(cb['number'],16),'timestamp_UTC':stamp(cb),'status':'success','transfer_event':credit,'Hyperliquid_account':V,'Hyperliquid_deposit_record':deposit,'matching_parameters':['identical transaction hash','identical USDC amount','account queried equals on-chain source'],'allocation_provenance':'PARTIAL / RE-ESTABLISHED token boundary: zero balance before fulfillment, full receipt transfer then exact full deposit. Complete lifetime/history allocation remains limited by later historical-state errors and bounded log window; upstream Ethereum pool remains MIXED.','history_window_start_block':int(db['number'],16),'history_window_end_block':int(r('destination_window_end')['number'],16),'history_window_end_timestamp_UTC':stamp(r('destination_window_end')),'historical_state_limit':'Pre/post Hyperliquid transaction and window-end state calls failed; saved errors are not missing activity. Bounded logs contain one positive source outflow plus a later zero-value lookalike transfer, not a second debit.','evidence_files':ef('credit_tx','credit_receipt','credit_block','credit_endpoint_code','hyperliquid_credit','destination_outgoing_USDC_logs','destination_incoming_USDC_logs','destination_window_end','credit_pre_balance','credit_post_balance','destination_window_USDC_balance')+['../unlabeled_a3ca_verification_2026_10_09/README.md'],'attribution_significance':'Named Hyperliquid service and exact account credit, not user identity, custody owner or final beneficiary. Does not change six Relay route totals or existing XMR1 accounting.'})
spot=next(x for x in api if x['delta']['type']=='accountClassTransfer' and not x['delta']['toPerp']);add({'classification':'CONFIRMED','record_type':'Hyperliquid internal account transfer, not external conversion/withdrawal','Hyperliquid_account':V,'API_record':spot,'asset':'USDC','amount':'26823.2','destination_account_class':'spot','evidence_files':ef('hyperliquid_credit'),'attribution_significance':'Internal USDC movement only. No fresh spot fills, XMR1 holdings, native XMR redemption or external withdrawal asserted.'})
rt=dr('router_tx');rq=dr('router_receipt');top=dr('supplement_tx');gas=int(rq['gasUsed'],16)*int(rq['effectiveGasPrice'],16);fund=int(top['value'],16);principal=int(rt['value'],16);beforeprincipal=int(dr('onward_tx')['value'],16);assert principal==beforeprincipal and fund>gas
add({'classification':'SUPPORTED','record_type':'Special small-funding purpose and provenance test','source_wallet':F,'destination_wallet':V,'transaction_hash':top['hash'],'amount_ETH':units(fund),'amount_wei':str(fund),'timestamp_UTC':stamp(dr('supplement_block')),'router_principal_ETH':units(principal),'router_gas_ETH':units(gas),'additional_balance_necessary_for_amount_plus_gas_wei':str(gas),'balance_after_principal_and_gas_ETH':units(fund-gas),'fee_funding_interpretation':'SUPPORTED: pre-top-up ETH exactly equals subsequent attached trade value; positive gas requires extra liquidity. No extra principal was numerically necessary. Intent and fungible wei source assignment not proven.','source_account_type':'CONFIRMED EOA at case block','source_service_identity':'UNRESOLVED; metadata and protocol usage do not name its operator','provenance_effect':'Native second EOA is MIXED / two-inflow boundary; last-hop transfer/account continuity confirmed. Token output remains transaction-specific, upstream affected-wallet provenance unresolved.','evidence_files':ef('fee_source_case_code','fee_source_metadata','fee_source_case_history')+['../robinhood_disposal_2026_10_09/access/supplement_tx.response.txt','../robinhood_disposal_2026_10_09/access/supplement_receipt.response.txt','../robinhood_disposal_2026_10_09/access/router_receipt.response.txt'],'attribution_significance':'Necessary extra gas liquidity is not proof of common control, source identity, fee service identity or beneficiary.'})
known=set(x.lower() for x in re.findall(r'0x[0-9a-fA-F]{40}(?![0-9a-fA-F])',json.dumps(old)));funding=[]
for x in raw('fee_source_case_history')['result']:
 if x['to'] not in known or x['to']==F:continue
 h=x['hash'];t=r(h+'_tx');q=r(h+'_receipt');b=r('block_'+t['blockNumber']);funding.append(add({'classification':'CONFIRMED','record_type':'Verified common funding-source account edge; no common-control inference','existing_supplement_ID':'F0549' if h==top['hash'] else None,'chain':'Ethereum (1)','transaction_hash':h,'source_wallet':t['from'],'destination_wallet':t['to'],'asset':'native ETH','amount_wei':str(int(t['value'],16)),'amount_ETH':units(int(t['value'],16)),'block_number':int(b['number'],16),'timestamp_UTC':stamp(b),'status':'success','sender_nonce':int(t['nonce'],16),'input':t['input'],'evidence_files':ef(h+'_tx',h+'_receipt','block_'+t['blockNumber']),'attribution_significance':'Independent exact native transfer into an already-documented routing EOA. Common funding-source account is confirmed; fee-purpose for other transfers, service identity, common operator and private custody remain unresolved.'}))
assert len(funding)==10
add({'classification':'CONFIRMED','record_type':'Pooled interval test / source funding relationship summary','known_15_Robinhood_credit_ETH':'213.164462838697324465','known_seven_contract_mediated_credit_wei':str(sum(int(x['destination_amount_wei']) for x in rh[8:])),'individual_outflows_forced_to_include_seven_group':sum(int(v['seven']['minimum_group_principal_wei'])>0 for v in bounds.values()),'individual_seven_ID_assignments':0,'seven_credit_paths_to_routing_wallet_complete':7,'seven_individual_end_to_end_disposal_allocations_complete':0,'seven_individual_end_to_end_disposal_allocations_incomplete':7,'additional_source_funding_relationship':'Ten exact transfers from the same fee-source EOA into ten documented downstream source EOAs; no direct transaction with 0x427c, 0x07ae or affected wallet in this bounded 33-transaction source history. Not a lifetime absence claim.','source_history_block_range':[26136700,26137480],'bound_method':'For each group, add only exact verified credits. Debit all outward principal+gas in chronological order; minimum group balance becomes max(0, prior minimum-total debit), maximum min(prior maximum, remaining balance). Minimum principal group contribution is max(0, minimum group balance before-(total balance before-principal)). No FIFO or timing allocation.','group_limit':'Some all-15-Robinhood group lower bounds may be positive; they do not force any of seven specific deposits into a disposal or establish affected-wallet provenance. Bounds apply only to reconciled captured account scope.','evidence_files':ef('fee_source_case_history','routing_transactions','routing_transactions_page_1','routing_internal-transactions'),'attribution_significance':'Account relations and conservative balance constraints only. No ownership/control/beneficiary promotion.'})
# Inventory existing native routes and service boundaries, keeping pool stop points explicit.
allhops=[x for x in oldnative if 152<=int(x['ID'][1:])<=180];inventory=[]
for t,q,b in sorted(out,key=lambda z:int(z[0]['nonce'],16)):
 seen=set();reachable=[]
 def walk(addr,depth=0):
  if addr in seen or depth>5:return
  seen.add(addr)
  for x in allhops:
   if x['source'].lower()==addr:
    reachable.append(x['ID']);walk(x['destination'].lower(),depth+1)
 walk(t['to']);inventory.append({'routing_outflow_hash':t['hash'],'routing_nonce':int(t['nonce'],16),'recipient':t['to'],'verified_existing_native_hop_IDs':reachable,'allocation':'Account-level reachable graph, not individual seven-fill allocation','shared_pool_warning':t['to']=='0x40ac40f33d32a8ffd808cbbbf02524b6d834b811'})
add({'classification':'CONFIRMED','record_type':'Scoped disposal path inventory, existing protocol routes retained','routing_outflows_reproduced':15,'legacy_onward_transactions_reproduced':len(allhops),'existing_LIFI_routes':'Six Relay + one Across + three Mayan = ten existing confirmed source routes. No new bridge route in this block.','existing_other_boundaries':'Two Chainflip routes; NEAR Intents route; dated 4 ETH holding EOA; pooled forwarding/collector boundaries. Previously verified protocol roles remain distinct.','inventory':inventory,'funding_provenance':'MIXED routing-wallet boundary; native edge reproduction and protocol route confirmation do not create per-seven-deposit assignment','next_highest_priority_target':'Robinhood native token-sale payout tracing / historical state to resolve complete affected-wallet upstream provenance; only transaction-specific protocol or state evidence can improve individual allocations. No other branch opened.','remaining_gaps':['Complete Robinhood origin-side native funding provenance','Specific seven-deposit allocation through Ethereum pool','Fee-source service/operator identity and signer authorization/control','Native provenance through downstream pooled collectors; account holder and beneficiary'], 'preservation':'Frozen v0.1 and prior F objects unchanged. No article. Privacy Cash separate. No new loss totals.','evidence_files':['../mayan_verification_2026_10_09/cross_chain_edges.json','../robinhood_linkage_2026_10_09/cross_chain_edges.json']})
assert rows[-1]['ID']=='F0585'
hopdetails=[]
for x in allhops:
 h=x['tx/signature'];t=r(h+'_tx');q=r(h+'_receipt');b=r('block_'+t['blockNumber']);hopdetails.append({'existing_ID':x['ID'],'transaction_hash':h,'source':t['from'],'destination':t['to'],'asset':'native ETH','amount_wei':str(int(t['value'],16)),'block_number':int(t['blockNumber'],16),'timestamp_UTC':stamp(b),'status':'success','sender_case_code':r(h+'_sender_code'),'recipient_case_code':r(h+'_recipient_code'),'sender_pre_block_balance_wei':str(int(r(h+'_sender_pre_balance'),16)),'gas_wei':str(int(q['gasUsed'],16)*int(q['effectiveGasPrice'],16)),'calldata':t['input'],'evidence_files':ef(h+'_tx',h+'_receipt','block_'+t['blockNumber'],h+'_sender_code',h+'_recipient_code',h+'_sender_pre_balance'),'classification':'CONFIRMED','provenance':'Direct native hop only; pool attribution separately constrained'})
dump('legacy_native_hop_reproductions.json',hopdetails)
dump('ledger_F0553_F0585.json',rows);dump('master_timeline_F0001_F0585.json',{'notes':'Prior 552 objects unchanged. Append-only deduplication; scope accounting and Hyperliquid deposit confirmation do not create new bridge routes or losses.','rows':old+rows});dump('pool_accounting.json',{'summary':summary,'chronological_events':account,'outflow_group_bounds':bounds});dump('funding_edges.json',funding);dump('path_inventory.json',inventory)
